Repository javascript-tutorial/zh.javascript.info, pull requests merged in 2018-04, with the labels that each got.

#36 1-js/03-code-quality/02-coding-style
  1-js/03-code-quality/02-coding-style/article.md
Labels: 正在校对

#29 1-js/01-getting-started/
  1-js/01-getting-started/1-intro/article.md
  1-js/01-getting-started/2-code-editors/article.md
  1-js/01-getting-started/3-devtools/article.md
  1-js/01-getting-started/index.md
Labels: 正在校对

#30 1-js/02-first-steps/01-hello-world/
  1-js/02-first-steps/01-hello-world/1-hello-alert/task.md
  1-js/02-first-steps/01-hello-world/2-hello-alert-ext/solution.md
  1-js/02-first-steps/01-hello-world/2-hello-alert-ext/task.md
  1-js/02-first-steps/01-hello-world/article.md
Labels: 正在校对

#37 1-js/03-code-quality/03-comments
  1-js/03-code-quality/03-comments/article.md
Labels: 翻译完成

#31 1-js/02-first-steps/02-structure and 03-strict-mode
  1-js/02-first-steps/02-structure/article.md
  1-js/02-first-steps/03-strict-mode/article.md
Labels: 校对认领

#53 1-js/02-first-steps/09-alert-prompt-confirm
  1-js/02-first-steps/09-alert-prompt-confirm/1-simple-page/solution.md
  1-js/02-first-steps/09-alert-prompt-confirm/1-simple-page/task.md
  1-js/02-first-steps/09-alert-prompt-confirm/article.md
Labels: 正在校对, 翻译完成

#49 操作符
  1-js/02-first-steps/07-operators/1-increment-order/solution.md
  1-js/02-first-steps/07-operators/1-increment-order/task.md
  1-js/02-first-steps/07-operators/2-assignment-result/solution.md
  1-js/02-first-steps/07-operators/2-assignment-result/task.md
  1-js/02-first-steps/07-operators/article.md
Labels: 正在校对, 翻译完成

#48 1-js/04-object-basics/04-object-methods
  1-js/04-object-basics/04-object-methods/2-check-syntax/solution.md
  1-js/04-object-basics/04-object-methods/2-check-syntax/task.md
  1-js/04-object-basics/04-object-methods/3-why-this/solution.md
  1-js/04-object-basics/04-object-methods/3-why-this/task.md
  1-js/04-object-basics/04-object-methods/4-object-property-this/solution.md
  1-js/04-object-basics/04-object-methods/4-object-property-this/task.md
  1-js/04-object-basics/04-object-methods/7-calculator/task.md
  1-js/04-object-basics/04-object-methods/8-chain-calls/solution.md
  1-js/04-object-basics/04-object-methods/8-chain-calls/task.md
  1-js/04-object-basics/04-object-methods/article.md
Labels: 正在校对, 翻译完成

#43 1-js/02-first-steps/13-switch
  1-js/02-first-steps/13-switch/1-rewrite-switch-if-else/solution.md
  1-js/02-first-steps/13-switch/1-rewrite-switch-if-else/task.md
  1-js/02-first-steps/13-switch/2-rewrite-if-switch/solution.md
  1-js/02-first-steps/13-switch/2-rewrite-if-switch/task.md
  1-js/02-first-steps/13-switch/article.md
Labels: 正在校对

#47 函数表达式和箭头函数
  1-js/02-first-steps/15-function-expressions-arrows/1-rewrite-arrow/solution.md
  1-js/02-first-steps/15-function-expressions-arrows/1-rewrite-arrow/task.md
  1-js/02-first-steps/15-function-expressions-arrows/article.md
Labels: 正在校对

#39 1-js/03-code-quality/05-testing-mocha
  1-js/03-code-quality/05-testing-mocha/3-pow-test-wrong/solution.md
  1-js/03-code-quality/05-testing-mocha/3-pow-test-wrong/task.md
  1-js/03-code-quality/05-testing-mocha/article.md
Labels: 正在校对

#34 1-js/02-first-steps/06-type-conversions
  1-js/02-first-steps/06-type-conversions/1-primitive-conversions-questions/solution.md
  1-js/02-first-steps/06-type-conversions/1-primitive-conversions-questions/task.md
  1-js/02-first-steps/06-type-conversions/article.md
Labels: 正在校对

#38 1-js/03-code-quality/04-ninja-code
  1-js/03-code-quality/04-ninja-code/article.md
Labels: 正在校对

#33 1-js/02-first-steps/05-types
  1-js/02-first-steps/05-types/1-string-quotes/solution.md
  1-js/02-first-steps/05-types/1-string-quotes/task.md
  1-js/02-first-steps/05-types/article.md
Labels: 正在校对

#40 1-js/03-code-quality/06-polyfills
  1-js/03-code-quality/06-polyfills/article.md
Labels: 正在校对

#35 1-js/03-code-quality/01-debugging-chrome
  1-js/03-code-quality/01-debugging-chrome/article.md
Labels: 正在校对

#44 02-garbage-collection
  1-js/04-object-basics/02-garbage-collection/article.md
Labels: 正在校对

#51 Translation/1 js/02 first steps/12 while for
  1-js/02-first-steps/12-while-for/1-loop-last-value/solution.md
  1-js/02-first-steps/12-while-for/1-loop-last-value/task.md
  1-js/02-first-steps/12-while-for/2-which-value-while/solution.md
  1-js/02-first-steps/12-while-for/2-which-value-while/task.md
  1-js/02-first-steps/12-while-for/3-which-value-for/solution.md
  1-js/02-first-steps/12-while-for/3-which-value-for/task.md
  1-js/02-first-steps/12-while-for/4-for-even/solution.md
  1-js/02-first-steps/12-while-for/4-for-even/task.md
  1-js/02-first-steps/12-while-for/5-replace-for-while/task.md
  1-js/02-first-steps/12-while-for/6-repeat-until-correct/solution.md
  1-js/02-first-steps/12-while-for/6-repeat-until-correct/task.md
  1-js/02-first-steps/12-while-for/7-list-primes/solution.md
  1-js/02-first-steps/12-while-for/7-list-primes/task.md
  1-js/02-first-steps/12-while-for/article.md
Labels: 校对认领, 正在校对

#50 1-js/02-first-steps/08-comparison
  1-js/02-first-steps/08-comparison/1-comparison-questions/solution.md
  1-js/02-first-steps/08-comparison/1-comparison-questions/task.md
  1-js/02-first-steps/08-comparison/article.md
Labels: 正在校对

#55 1-02-11-逻辑运算符
  1-js/02-first-steps/11-logical-operators/1-alert-null-2-undefined/solution.md
  1-js/02-first-steps/11-logical-operators/1-alert-null-2-undefined/task.md
  1-js/02-first-steps/11-logical-operators/2-alert-or/solution.md
  1-js/02-first-steps/11-logical-operators/2-alert-or/task.md
  1-js/02-first-steps/11-logical-operators/3-alert-1-null-2/solution.md
  1-js/02-first-steps/11-logical-operators/3-alert-1-null-2/task.md
  1-js/02-first-steps/11-logical-operators/4-alert-and/solution.md
  1-js/02-first-steps/11-logical-operators/4-alert-and/task.md
  1-js/02-first-steps/11-logical-operators/5-alert-and-or/solution.md
  1-js/02-first-steps/11-logical-operators/5-alert-and-or/task.md
  1-js/02-first-steps/11-logical-operators/6-check-if-in-range/task.md
  1-js/02-first-steps/11-logical-operators/7-check-if-out-range/solution.md
  1-js/02-first-steps/11-logical-operators/7-check-if-out-range/task.md
  1-js/02-first-steps/11-logical-operators/8-if-question/solution.md
  1-js/02-first-steps/11-logical-operators/8-if-question/task.md
  1-js/02-first-steps/11-logical-operators/article.md
Labels: 正在校对

#41 Symbol 类型
  1-js/04-object-basics/03-symbol/article.md
Labels: 正在校对
