Repository javascript-tutorial/zh.javascript.info, pull requests merged in 2018-06, with the labels that each got.

#113 1-js/06-advanced-functions/11-currying-partials
  1-js/06-advanced-functions/11-currying-partials/1-ask-currying/solution.md
  1-js/06-advanced-functions/11-currying-partials/1-ask-currying/task.md
  1-js/06-advanced-functions/11-currying-partials/article.md
Labels: WIP, 校对认领, 正在校对

#101 1 js/05 data types/05 array methods
  1-js/05-data-types/01-primitives-methods/1-string-new-property/solution.md
  1-js/05-data-types/01-primitives-methods/article.md
  1-js/05-data-types/05-array-methods/1-camelcase/task.md
  1-js/05-data-types/05-array-methods/10-average-age/task.md
  1-js/05-data-types/05-array-methods/11-array-unique/solution.md
  1-js/05-data-types/05-array-methods/11-array-unique/task.md
  1-js/05-data-types/05-array-methods/2-filter-range/task.md
  1-js/05-data-types/05-array-methods/3-filter-range-in-place/task.md
  1-js/05-data-types/05-array-methods/4-sort-back/task.md
  1-js/05-data-types/05-array-methods/5-copy-sort-array/solution.md
  1-js/05-data-types/05-array-methods/5-copy-sort-array/task.md
  1-js/05-data-types/05-array-methods/6-array-get-names/task.md
  1-js/05-data-types/05-array-methods/7-map-objects/solution.md
  1-js/05-data-types/05-array-methods/7-map-objects/task.md
  1-js/05-data-types/05-array-methods/8-sort-objects/solution.md
  1-js/05-data-types/05-array-methods/8-sort-objects/task.md
  1-js/05-data-types/05-array-methods/9-shuffle/solution.md
  1-js/05-data-types/05-array-methods/9-shuffle/task.md
  1-js/05-data-types/05-array-methods/article.md
Labels: WIP, 校对认领, 正在校对

#109 1-js/07-object-oriented-programming/08-class-patterns/
  1-js/07-object-oriented-programming/08-class-patterns/1-inheritance-error-assign/solution.md
  1-js/07-object-oriented-programming/08-class-patterns/1-inheritance-error-assign/task.md
  1-js/07-object-oriented-programming/08-class-patterns/2-rewrite-to-prototypes/solution.md
  1-js/07-object-oriented-programming/08-class-patterns/2-rewrite-to-prototypes/task.md
  1-js/07-object-oriented-programming/08-class-patterns/article.md
Labels: WIP, 校对认领, 正在校对

#117 1 js/05 data types/04 array
  1-js/05-data-types/04-array/1-item-value/solution.md
  1-js/05-data-types/04-array/1-item-value/task.md
  1-js/05-data-types/04-array/10-maximal-subarray/solution.md
  1-js/05-data-types/04-array/10-maximal-subarray/task.md
  1-js/05-data-types/04-array/2-create-array/task.md
  1-js/05-data-types/04-array/3-call-array-this/solution.md
  1-js/05-data-types/04-array/3-call-array-this/task.md
  1-js/05-data-types/04-array/5-array-input-sum/solution.md
  1-js/05-data-types/04-array/5-array-input-sum/task.md
  1-js/05-data-types/04-array/article.md
Labels: WIP, 校对认领, 正在校对

#121 1-js/07-object-oriented-programming/13-mixins
  1-js/07-object-oriented-programming/13-mixins/article.md
  1-js/07-object-oriented-programming/13-mixins/head.html
Labels: 翻译完成

#118 1-js/06-advanced-functions/08-settimeout-setinterval
  1-js/06-advanced-functions/08-settimeout-setinterval/1-output-numbers-100ms/solution.md
  1-js/06-advanced-functions/08-settimeout-setinterval/1-output-numbers-100ms/task.md
  1-js/06-advanced-functions/08-settimeout-setinterval/3-rewrite-settimeout/task.md
  1-js/06-advanced-functions/08-settimeout-setinterval/4-settimeout-result/solution.md
  1-js/06-advanced-functions/08-settimeout-setinterval/4-settimeout-result/task.md
  1-js/06-advanced-functions/08-settimeout-setinterval/article.md
Labels: WIP, 正在校对

#111 1-js/04-object-basics/05-object-toprimitive
  1-js/04-object-basics/05-object-toprimitive/article.md
Labels: WIP, 校对认领, 正在校对

#115 1-js/08-error-handling/2-custom-errors
  1-js/08-error-handling/2-custom-errors/1-format-error/task.md
  1-js/08-error-handling/2-custom-errors/article.md
Labels: WIP, 正在校对

#112 1 js/07 object oriented programming/09 class
  1-js/07-object-oriented-programming/09-class/1-rewrite-to-class/task.md
  1-js/07-object-oriented-programming/09-class/article.md
Labels: 翻译完成
