Repository javascript-tutorial/zh.javascript.info, pull requests merged in 2018-07, with the labels that each got.

#140 对象的键、值、项
  1-js/05-data-types/08-keys-values-entries/01-sum-salaries/task.md
  1-js/05-data-types/08-keys-values-entries/02-count-properties/task.md
  1-js/05-data-types/08-keys-values-entries/article.md
Labels: WIP, 正在校对

#124 1 js/04 object basics/06 constructor new
  1-js/04-object-basics/06-constructor-new/1-two-functions-one-object/solution.md
  1-js/04-object-basics/06-constructor-new/1-two-functions-one-object/task.md
  1-js/04-object-basics/06-constructor-new/2-calculator-constructor/task.md
  1-js/04-object-basics/06-constructor-new/3-accumulator/task.md
  1-js/04-object-basics/06-constructor-new/4-calculator-extendable/solution.md
  1-js/04-object-basics/06-constructor-new/4-calculator-extendable/task.md
  1-js/04-object-basics/06-constructor-new/article.md
Labels: 翻译完成

#116 1-js/08-error-handling/1-try-catch/
  1-js/08-error-handling/1-try-catch/1-finally-or-code-after/solution.md
  1-js/08-error-handling/1-try-catch/1-finally-or-code-after/task.md
  1-js/08-error-handling/1-try-catch/article.md
Labels: 翻译完成

#149 2-ui/1-document/01-browser-environment and 02-dom-nodes
  2-ui/1-document/01-browser-environment/article.md
  2-ui/1-document/02-dom-nodes/article.md
Labels: WIP, 校对认领

#141 1-js/06-advanced-functions/03-closure
  1-js/06-advanced-functions/03-closure/1-counter-independent/solution.md
  1-js/06-advanced-functions/03-closure/1-counter-independent/task.md
  1-js/06-advanced-functions/03-closure/2-counter-object-independent/solution.md
  1-js/06-advanced-functions/03-closure/2-counter-object-independent/task.md
  1-js/06-advanced-functions/03-closure/3-function-in-if/solution.md
  1-js/06-advanced-functions/03-closure/3-function-in-if/task.md
  1-js/06-advanced-functions/03-closure/4-closure-sum/solution.md
  1-js/06-advanced-functions/03-closure/4-closure-sum/task.md
  1-js/06-advanced-functions/03-closure/6-filter-through-function/solution.md
  1-js/06-advanced-functions/03-closure/6-filter-through-function/task.md
  1-js/06-advanced-functions/03-closure/7-sort-by-field/task.md
  1-js/06-advanced-functions/03-closure/8-make-army/solution.md
  1-js/06-advanced-functions/03-closure/8-make-army/task.md
  1-js/06-advanced-functions/03-closure/article.md
Labels: WIP, 正在校对

#110 1-js/07-object-oriented-programming/11-instanceof/
  1-js/07-object-oriented-programming/11-instanceof/1-strange-instanceof/solution.md
  1-js/07-object-oriented-programming/11-instanceof/1-strange-instanceof/task.md
  1-js/07-object-oriented-programming/11-instanceof/article.md
Labels: WIP, 校对认领, 正在校对

#119 1 js/06 advanced functions/12 arrow functions/article.md
  1-js/06-advanced-functions/12-arrow-functions/article.md
Labels: 翻译完成

#143 1-js/04-object-basics/01-object
  1-js/04-object-basics/01-object/2-hello-object/task.md
  1-js/04-object-basics/01-object/3-is-empty/_js.view/solution.js
  1-js/04-object-basics/01-object/3-is-empty/solution.md
  1-js/04-object-basics/01-object/3-is-empty/task.md
  1-js/04-object-basics/01-object/4-const-object/solution.md
  1-js/04-object-basics/01-object/4-const-object/task.md
  1-js/04-object-basics/01-object/5-sum-object/task.md
  1-js/04-object-basics/01-object/8-multiply-numeric/_js.view/source.js
  1-js/04-object-basics/01-object/8-multiply-numeric/task.md
  1-js/04-object-basics/01-object/article.md
Labels: WIP, 校对认领, 正在校对

#147 Translation/prototype inheritance
  1-js/07-object-oriented-programming/03-prototype-inheritance/1-property-after-delete/solution.md
  1-js/07-object-oriented-programming/03-prototype-inheritance/1-property-after-delete/task.md
  1-js/07-object-oriented-programming/03-prototype-inheritance/2-search-algorithm/solution.md
  1-js/07-object-oriented-programming/03-prototype-inheritance/2-search-algorithm/task.md
  1-js/07-object-oriented-programming/03-prototype-inheritance/3-proto-and-this/solution.md
  1-js/07-object-oriented-programming/03-prototype-inheritance/3-proto-and-this/task.md
  1-js/07-object-oriented-programming/03-prototype-inheritance/4-hamster-proto/solution.md
  1-js/07-object-oriented-programming/03-prototype-inheritance/4-hamster-proto/task.md
  1-js/07-object-oriented-programming/03-prototype-inheritance/article.md
Labels: WIP, 校对认领, 正在校对

#123 javascript-tutorial-en/1-js/07-object-oriented-programming/05-native-prototypes/
  1-js/07-object-oriented-programming/05-native-prototypes/1-defer-to-prototype/task.md
  1-js/07-object-oriented-programming/05-native-prototypes/2-defer-to-prototype-extended/task.md
  1-js/07-object-oriented-programming/05-native-prototypes/article.md
Labels: WIP, enhancement, 校对认领, 正在校对

#145 DOM 特性和属性
  2-ui/1-document/06-dom-attributes-and-properties/article.md
Labels: WIP, 校对认领, 正在校对

#144 Translation/searching
  2-ui/1-document/04-searching-elements-dom/1-find-elements/solution.md
  2-ui/1-document/04-searching-elements-dom/1-find-elements/task.md
  2-ui/1-document/04-searching-elements-dom/2-tree-info/solution.md
  2-ui/1-document/04-searching-elements-dom/2-tree-info/task.md
  2-ui/1-document/04-searching-elements-dom/article.md
Labels: WIP, 校对认领, 正在校对
