Repository javascript-tutorial/zh.javascript.info, pull requests merged in 2018-10, with the labels that each got.

#214 2-ui/4-forms-controls/3-events-change-input and 4-forms-submit
  2-ui/4-forms-controls/3-events-change-input/1-deposit-calculator/task.md
  2-ui/4-forms-controls/3-events-change-input/article.md
  2-ui/4-forms-controls/4-forms-submit/1-modal-dialog/solution.md
  2-ui/4-forms-controls/4-forms-submit/1-modal-dialog/task.md
  2-ui/4-forms-controls/4-forms-submit/article.md
Labels: WIP, 校对认领, 正在校对

#201 Update article.md
  2-ui/1-document/10-size-and-scroll-window/article.md
Labels: WIP, 校对认领, 正在校对

#205 Translate js animation
  3-animation/3-js-animation/1-animate-ball/solution.md
  3-animation/3-js-animation/1-animate-ball/task.md
  3-animation/3-js-animation/2-animate-ball-hops/solution.md
  3-animation/3-js-animation/2-animate-ball-hops/task.md
  3-animation/3-js-animation/article.md
Labels: WIP, 正在校对

#249 Translation/5 regular expressions/15 regexp infinite backtracking problem
  5-regular-expressions/15-regexp-infinite-backtracking-problem/article.md
Labels: WIP, 正在校对

#194 07-修改文档
  2-ui/1-document/07-modifying-document/1-createtextnode-vs-innerhtml/solution.md
  2-ui/1-document/07-modifying-document/1-createtextnode-vs-innerhtml/task.md
  2-ui/1-document/07-modifying-document/10-clock-setinterval/solution.md
  2-ui/1-document/07-modifying-document/10-clock-setinterval/task.md
  2-ui/1-document/07-modifying-document/11-append-to-list/solution.md
  2-ui/1-document/07-modifying-document/11-append-to-list/task.md
  2-ui/1-document/07-modifying-document/12-sort-table/solution.md
  2-ui/1-document/07-modifying-document/12-sort-table/task.md
  2-ui/1-document/07-modifying-document/4-clear-elem/solution.md
  2-ui/1-document/07-modifying-document/4-clear-elem/task.md
  2-ui/1-document/07-modifying-document/5-why-aaa/solution.md
  2-ui/1-document/07-modifying-document/5-why-aaa/task.md
  2-ui/1-document/07-modifying-document/6-create-list/solution.md
  2-ui/1-document/07-modifying-document/6-create-list/task.md
  2-ui/1-document/07-modifying-document/7-create-object-tree/solution.md
  2-ui/1-document/07-modifying-document/7-create-object-tree/task.md
  2-ui/1-document/07-modifying-document/8-tree-count/solution.md
  2-ui/1-document/07-modifying-document/8-tree-count/task.md
  2-ui/1-document/07-modifying-document/9-calendar-table/solution.md
  2-ui/1-document/07-modifying-document/9-calendar-table/task.md
  2-ui/1-document/07-modifying-document/article.md
Labels: WIP, 校对认领, 正在校对

#153 Translation/dom node properties
  2-ui/1-document/05-basic-dom-node-properties/2-lastchild-nodetype-inline/solution.md
  2-ui/1-document/05-basic-dom-node-properties/2-lastchild-nodetype-inline/task.md
  2-ui/1-document/05-basic-dom-node-properties/3-tag-in-comment/solution.md
  2-ui/1-document/05-basic-dom-node-properties/3-tag-in-comment/task.md
  2-ui/1-document/05-basic-dom-node-properties/4-where-document-in-hierarchy/solution.md
  2-ui/1-document/05-basic-dom-node-properties/4-where-document-in-hierarchy/task.md
  2-ui/1-document/05-basic-dom-node-properties/article.md
Labels: WIP, 正在校对

#179 Translation/onload ondomcontentloaded
  2-ui/3-event-details/10-onload-ondomcontentloaded/article.md
Labels: WIP, 正在校对

#180 Translation/keyboard events
  2-ui/3-event-details/5-keyboard-events/2-check-sync-keydown/solution.md
  2-ui/3-event-details/5-keyboard-events/2-check-sync-keydown/task.md
  2-ui/3-event-details/5-keyboard-events/article.md
Labels: WIP, 正在校对

#254 点击劫持攻击
  4-frames-and-windows/06-clickjacking/article.md
Labels: WIP, 正在校对

#255 translation/06-async/03-promise-chaining
  6-async/03-promise-chaining/01-then-vs-catch/solution.md
  6-async/03-promise-chaining/01-then-vs-catch/task.md
  6-async/03-promise-chaining/02-error-async/solution.md
  6-async/03-promise-chaining/02-error-async/task.md
  6-async/03-promise-chaining/article.md
Labels: WIP, 校对认领, 正在校对

#160 Translation/event delegation
  2-ui/2-events/03-event-delegation/1-hide-message-delegate/task.md
  2-ui/2-events/03-event-delegation/2-sliding-tree/solution.md
  2-ui/2-events/03-event-delegation/2-sliding-tree/task.md
  2-ui/2-events/03-event-delegation/3-sortable-table/task.md
  2-ui/2-events/03-event-delegation/4-behavior-tooltip/task.md
  2-ui/2-events/03-event-delegation/article.md
Labels: WIP, 正在校对

#163 Translation/default browser action
  2-ui/2-events/04-default-browser-action/1-why-return-false-fails/solution.md
  2-ui/2-events/04-default-browser-action/1-why-return-false-fails/task.md
  2-ui/2-events/04-default-browser-action/2-catch-link-navigation/solution.md
  2-ui/2-events/04-default-browser-action/2-catch-link-navigation/task.md
  2-ui/2-events/04-default-browser-action/3-image-gallery/solution.md
  2-ui/2-events/04-default-browser-action/3-image-gallery/task.md
  2-ui/2-events/04-default-browser-action/article.md
Labels: WIP, 正在校对

#256 Translation/archive/01 hello world and archive/02 external script
  archive/01-hello-world/article.md
  archive/02-external-script/article.md
Labels: WIP, 正在校对

#206 聚焦和去焦
  2-ui/4-forms-controls/2-focus-blur/3-editable-div/task.md
  2-ui/4-forms-controls/2-focus-blur/4-edit-td-click/solution.md
  2-ui/4-forms-controls/2-focus-blur/4-edit-td-click/task.md
  2-ui/4-forms-controls/2-focus-blur/5-keyboard-mouse/solution.md
  2-ui/4-forms-controls/2-focus-blur/5-keyboard-mouse/task.md
  2-ui/4-forms-controls/2-focus-blur/article.md
Labels: WIP, enhancement, 正在校对

#237 贪婪量词和惰性量词
  5-regular-expressions/08-regexp-greedy-and-lazy/1-lazy-greedy/solution.md
  5-regular-expressions/08-regexp-greedy-and-lazy/1-lazy-greedy/task.md
  5-regular-expressions/08-regexp-greedy-and-lazy/3-find-html-comments/solution.md
  5-regular-expressions/08-regexp-greedy-and-lazy/3-find-html-comments/task.md
  5-regular-expressions/08-regexp-greedy-and-lazy/4-find-html-tags-greedy-lazy/solution.md
  5-regular-expressions/08-regexp-greedy-and-lazy/4-find-html-tags-greedy-lazy/task.md
  5-regular-expressions/08-regexp-greedy-and-lazy/article.md
Labels: 翻译完成

#257 Translation/5-09-regexp-groups
  5-regular-expressions/09-regexp-groups/1-find-webcolor-3-or-6/solution.md
  5-regular-expressions/09-regexp-groups/1-find-webcolor-3-or-6/task.md
  5-regular-expressions/09-regexp-groups/3-find-decimal-positive-numbers/solution.md
  5-regular-expressions/09-regexp-groups/3-find-decimal-positive-numbers/task.md
  5-regular-expressions/09-regexp-groups/4-find-decimal-numbers/solution.md
  5-regular-expressions/09-regexp-groups/4-find-decimal-numbers/task.md
  5-regular-expressions/09-regexp-groups/5-parse-expression/solution.md
  5-regular-expressions/09-regexp-groups/5-parse-expression/task.md
  5-regular-expressions/09-regexp-groups/article.md
  5-regular-expressions/09-regexp-groups/regexp-nested-groups.png
  5-regular-expressions/09-regexp-groups/regexp-nested-groups@2x.png
Labels: WIP, 正在校对

#258 translate for removed project of 2-ui/4-forms-controls/1-form-elements, 2-ui/4-forms-controls/index.md and 2-ui/index.md #207
  2-ui/4-forms-controls/1-form-elements/1-add-select-option/solution.md
  2-ui/4-forms-controls/1-form-elements/1-add-select-option/task.md
  2-ui/4-forms-controls/1-form-elements/article.md
  2-ui/4-forms-controls/index.md
Labels: WIP, wontfix, 正在校对

#259 Translate/7 network
  7-network/1-xmlhttprequest/article.md
Labels: WIP, 正在校对

#183 Translation/onscroll
  2-ui/3-event-details/3-mousemove-mouseover-mouseout-mouseenter-mouseleave/1-behavior-nested-tooltip/task.md
  2-ui/3-event-details/3-mousemove-mouseover-mouseout-mouseenter-mouseleave/2-hoverintent/solution.md
  2-ui/3-event-details/3-mousemove-mouseover-mouseout-mouseenter-mouseleave/2-hoverintent/task.md
  2-ui/3-event-details/3-mousemove-mouseover-mouseout-mouseenter-mouseleave/article.md
  2-ui/3-event-details/8-onscroll/1-endless-page/solution.md
  2-ui/3-event-details/8-onscroll/1-endless-page/task.md
  2-ui/3-event-details/8-onscroll/2-updown-button/task.md
  2-ui/3-event-details/8-onscroll/3-load-visible-img/solution.md
  2-ui/3-event-details/8-onscroll/3-load-visible-img/task.md
  2-ui/3-event-details/8-onscroll/article.md
  2-ui/3-event-details/index.md
Labels: WIP, 正在校对

#266 5-regular-expressions/12-regexp-anchors, 3-regexp-multiline-mode/arti…
  5-regular-expressions/12-regexp-anchors/1-start-end/solution.md
  5-regular-expressions/12-regexp-anchors/1-start-end/task.md
  5-regular-expressions/12-regexp-anchors/2-test-mac/solution.md
  5-regular-expressions/12-regexp-anchors/2-test-mac/task.md
  5-regular-expressions/12-regexp-anchors/article.md
  5-regular-expressions/13-regexp-multiline-mode/article.md
  5-regular-expressions/14-regexp-lookahead/article.md
  5-regular-expressions/index.md
Labels: WIP, 校对认领, 正在校对

#267 5-regular-expressions/10-regexp-backreferences/article.md and 5-regular-expressions/11-regexp-alternation
  5-regular-expressions/10-regexp-backreferences/article.md
  5-regular-expressions/11-regexp-alternation/01-find-programming-language/solution.md
  5-regular-expressions/11-regexp-alternation/01-find-programming-language/task.md
  5-regular-expressions/11-regexp-alternation/02-find-matching-bbtags/solution.md
  5-regular-expressions/11-regexp-alternation/02-find-matching-bbtags/task.md
  5-regular-expressions/11-regexp-alternation/03-match-quoted-string/solution.md
  5-regular-expressions/11-regexp-alternation/03-match-quoted-string/task.md
  5-regular-expressions/11-regexp-alternation/04-match-exact-tag/solution.md
  5-regular-expressions/11-regexp-alternation/04-match-exact-tag/task.md
  5-regular-expressions/11-regexp-alternation/article.md
Labels: WIP, 校对认领, 正在校对
