Repository javascript-tutorial/zh.javascript.info, pull requests merged in 2018-09, with the labels that each got.

#216 跨窗口通信
  4-frames-and-windows/03-cross-window-communication/article.md
Labels: WIP, 正在校对

#213 2-ui/1-document/09-size-and-scroll
  2-ui/1-document/09-size-and-scroll/1-get-scroll-height-bottom/solution.md
  2-ui/1-document/09-size-and-scroll/1-get-scroll-height-bottom/task.md
  2-ui/1-document/09-size-and-scroll/2-scrollbar-width/solution.md
  2-ui/1-document/09-size-and-scroll/2-scrollbar-width/task.md
  2-ui/1-document/09-size-and-scroll/4-put-ball-in-center/solution.md
  2-ui/1-document/09-size-and-scroll/4-put-ball-in-center/task.md
  2-ui/1-document/09-size-and-scroll/6-width-vs-clientwidth/solution.md
  2-ui/1-document/09-size-and-scroll/6-width-vs-clientwidth/task.md
  2-ui/1-document/09-size-and-scroll/article.md
Labels: enhancement, 正在校对

#203 6-async/05-async-await
  6-async/05-async-await/01-rewrite-async-2/solution.md
  6-async/05-async-await/01-rewrite-async-2/task.md
  6-async/05-async-await/01-rewrite-async/solution.md
  6-async/05-async-await/01-rewrite-async/task.md
  6-async/05-async-await/article.md
Labels: WIP, 正在校对

#217 4-框架和窗口/01-弹窗 和 4-框架和窗口/index.md
  4-frames-and-windows/01-popup-windows/article.md
  4-frames-and-windows/index.md
Labels: 翻译完成

#233 07-正则表达式-量词
  5-regular-expressions/07-regexp-quantifiers/1-find-text-manydots/solution.md
  5-regular-expressions/07-regexp-quantifiers/1-find-text-manydots/task.md
  5-regular-expressions/07-regexp-quantifiers/2-find-html-colors-6hex/solution.md
  5-regular-expressions/07-regexp-quantifiers/2-find-html-colors-6hex/task.md
  5-regular-expressions/07-regexp-quantifiers/article.md
Labels: WIP, 校对认领, 正在校对

#212 3-2-CSS 动画
  3-animation/2-css-animations/1-animate-logo-css/solution.md
  3-animation/2-css-animations/1-animate-logo-css/task.md
  3-animation/2-css-animations/2-animate-logo-bezier-css/solution.md
  3-animation/2-css-animations/2-animate-logo-bezier-css/task.md
  3-animation/2-css-animations/3-animate-circle/task.md
  3-animation/2-css-animations/article.md
Labels: WIP, 正在校对

#211 3-animation/1-bezier-curve and 3-animation/index.md
  3-animation/1-bezier-curve/article.md
  3-animation/index.md
Labels: WIP, 校对认领, 正在校对

#226 5-regular-expressions/04-regexp-escaping/article.md、05-regexp-character-sets-and-ranges and 5-regular-expressions/06-regexp-unicode/article.md
  5-regular-expressions/04-regexp-escaping/article.md
  5-regular-expressions/05-regexp-character-sets-and-ranges/1-find-range-1/solution.md
  5-regular-expressions/05-regexp-character-sets-and-ranges/1-find-range-1/task.md
  5-regular-expressions/05-regexp-character-sets-and-ranges/2-find-time-2-formats/solution.md
  5-regular-expressions/05-regexp-character-sets-and-ranges/2-find-time-2-formats/task.md
  5-regular-expressions/05-regexp-character-sets-and-ranges/article.md
  5-regular-expressions/06-regexp-unicode/article.md
Labels: WIP, 正在校对

#224 Translation/5 regular expressions/03 regexp character classes
  5-regular-expressions/03-regexp-character-classes/1-find-time-hh-mm/task.md
  5-regular-expressions/03-regexp-character-classes/article.md
Labels: WIP, 正在校对
