Repository javascript-tutorial/zh.javascript.info, pull requests merged in 2018-08, with the labels that each got.

#178 Translation/mouse event
  2-ui/3-event-details/1-mouse-events-basics/01-selectable-list/task.md
  2-ui/3-event-details/1-mouse-events-basics/article.md
Labels: WIP, 校对认领, 正在校对

#162 Translation/dispatch events
  2-ui/2-events/05-dispatch-events/article.md
  2-ui/2-events/index.md
Labels: WIP, 校对认领, 正在校对

#161 Translation/bubbling and capturing
  2-ui/2-events/02-bubbling-and-capturing/article.md
Labels: WIP, 校对认领, 正在校对

#138 1-js/07-object-oriented-programming/10-class-inheritance
  1-js/07-object-oriented-programming/10-class-inheritance/1-class-constructor-error/solution.md
  1-js/07-object-oriented-programming/10-class-inheritance/1-class-constructor-error/task.md
  1-js/07-object-oriented-programming/10-class-inheritance/2-clock-class-extended/task.md
  1-js/07-object-oriented-programming/10-class-inheritance/3-class-extend-object/solution.md
  1-js/07-object-oriented-programming/10-class-inheritance/3-class-extend-object/task.md
  1-js/07-object-oriented-programming/10-class-inheritance/article.md
Labels: enhancement, 校对认领, 正在校对

#192 06-DOM 特性和属性
  2-ui/1-document/06-dom-attributes-and-properties/1-get-user-attribute/task.md
  2-ui/1-document/06-dom-attributes-and-properties/2-yellow-links/solution.md
  2-ui/1-document/06-dom-attributes-and-properties/2-yellow-links/task.md
  2-ui/1-document/06-dom-attributes-and-properties/article.md
Labels: 校对认领

#126 1-js/07-object-oriented-programming/01-property-descriptors and 02-property-accessors
  1-js/07-object-oriented-programming/01-property-descriptors/article.md
  1-js/07-object-oriented-programming/02-property-accessors/article.md
Labels: WIP, 校对认领, 正在校对

#127 1-js/07-object-oriented-programming/04-function-prototype
  1-js/07-object-oriented-programming/04-function-prototype/1-changing-prototype/solution.md
  1-js/07-object-oriented-programming/04-function-prototype/1-changing-prototype/task.md
  1-js/07-object-oriented-programming/04-function-prototype/4-new-object-same-constructor/solution.md
  1-js/07-object-oriented-programming/04-function-prototype/4-new-object-same-constructor/task.md
  1-js/07-object-oriented-programming/04-function-prototype/article.md
Labels: WIP, 校对认领, 正在校对

#177 1-js/06-advanced-functions/09-call-apply-decorators
  1-js/02-first-steps/01-hello-world/article.md
  1-js/06-advanced-functions/09-call-apply-decorators/01-spy-decorator/solution.md
  1-js/06-advanced-functions/09-call-apply-decorators/01-spy-decorator/task.md
  1-js/06-advanced-functions/09-call-apply-decorators/02-delay/solution.md
  1-js/06-advanced-functions/09-call-apply-decorators/02-delay/task.md
  1-js/06-advanced-functions/09-call-apply-decorators/03-debounce/solution.md
  1-js/06-advanced-functions/09-call-apply-decorators/03-debounce/task.md
  1-js/06-advanced-functions/09-call-apply-decorators/04-throttle/solution.md
  1-js/06-advanced-functions/09-call-apply-decorators/04-throttle/task.md
  1-js/06-advanced-functions/09-call-apply-decorators/article.md
Labels: WIP, 正在校对

#158 Translation/styles and classes
  2-ui/1-document/08-styles-and-classes/2-create-notification/task.md
  2-ui/1-document/08-styles-and-classes/article.md
Labels: 翻译完成

#168 Translation/dom navigation
  2-ui/1-document/03-dom-navigation/1-dom-children/solution.md
  2-ui/1-document/03-dom-navigation/1-dom-children/task.md
  2-ui/1-document/03-dom-navigation/3-navigation-links-which-null/solution.md
  2-ui/1-document/03-dom-navigation/3-navigation-links-which-null/task.md
  2-ui/1-document/03-dom-navigation/4-select-diagonal-cells/solution.md
  2-ui/1-document/03-dom-navigation/4-select-diagonal-cells/task.md
  2-ui/1-document/03-dom-navigation/article.md
  2-ui/1-document/11-coordinates/1-find-point-coordinates/solution.md
  2-ui/1-document/11-coordinates/1-find-point-coordinates/task.md
  2-ui/1-document/11-coordinates/2-position-at/solution.md
  2-ui/1-document/11-coordinates/2-position-at/task.md
  2-ui/1-document/11-coordinates/3-position-at-absolute/solution.md
  2-ui/1-document/11-coordinates/3-position-at-absolute/task.md
  2-ui/1-document/11-coordinates/4-position-inside-absolute/task.md
  2-ui/1-document/11-coordinates/article.md
Labels: WIP, 正在校对

#181 Translation/onload onerror
  2-ui/3-event-details/11-onload-onerror/1-load-img-callback/solution.md
  2-ui/3-event-details/11-onload-onerror/1-load-img-callback/task.md
  2-ui/3-event-details/11-onload-onerror/article.md
Labels: 翻译完成

#185 6-async/01-callbacks
  6-async/01-callbacks/01-animate-circle-callback/task.md
  6-async/01-callbacks/article.md
Labels: WIP, 校对认领, 正在校对

#186 6-async/02-promise-basics
  6-async/02-promise-basics/01-re-resolve/solution.md
  6-async/02-promise-basics/01-re-resolve/task.md
  6-async/02-promise-basics/02-delay-promise/solution.md
  6-async/02-promise-basics/02-delay-promise/task.md
  6-async/02-promise-basics/03-animate-circle-promise/task.md
  6-async/02-promise-basics/article.md
Labels: WIP, 校对认领, 正在校对

#210 contributors.md, LICENSE.md and README.md
  LICENSE.md
  README.md
  contributors.md
Labels: WIP, 正在校对
