Repository javascript-tutorial/zh.javascript.info, pull requests merged in 2018-05, with the labels that each got.

#80 1-js/06-advanced-functions/04-var
  1-js/06-advanced-functions/04-var/article.md
Labels: 正在校对

#76 日期
  1-js/05-data-types/10-date/1-new-date/solution.md
  1-js/05-data-types/10-date/1-new-date/task.md
  1-js/05-data-types/10-date/2-get-week-day/solution.md
  1-js/05-data-types/10-date/2-get-week-day/task.md
  1-js/05-data-types/10-date/3-weekday/solution.md
  1-js/05-data-types/10-date/3-weekday/task.md
  1-js/05-data-types/10-date/4-get-date-ago/solution.md
  1-js/05-data-types/10-date/4-get-date-ago/task.md
  1-js/05-data-types/10-date/5-last-day-of-month/task.md
  1-js/05-data-types/10-date/6-get-seconds-today/solution.md
  1-js/05-data-types/10-date/6-get-seconds-today/task.md
  1-js/05-data-types/10-date/7-get-seconds-to-tomorrow/solution.md
  1-js/05-data-types/10-date/7-get-seconds-to-tomorrow/task.md
  1-js/05-data-types/10-date/8-format-date-relative/solution.md
  1-js/05-data-types/10-date/8-format-date-relative/task.md
  1-js/05-data-types/10-date/article.md
Labels: 正在校对

#81 1-js/06-advanced-functions/05-global-object
  1-js/06-advanced-functions/05-global-object/article.md
Labels: 正在校对

#79 1 js/05 data types/11 json
  1-js/05-data-types/11-json/1-serialize-object/task.md
  1-js/05-data-types/11-json/2-serialize-event-circular/solution.md
  1-js/05-data-types/11-json/2-serialize-event-circular/task.md
  1-js/05-data-types/11-json/article.md
Labels: WIP, 正在校对

#78 1 js/05 data types/01 primitives methods
  1-js/05-data-types/01-primitives-methods/1-string-new-property/solution.md
  1-js/05-data-types/01-primitives-methods/1-string-new-property/task.md
  1-js/05-data-types/01-primitives-methods/article.md
Labels: WIP, 正在校对

#77 1-js/06-advanced-functions/07-new-function
  1-js/06-advanced-functions/07-new-function/article.md
Labels: 正在校对

#75 完成 1/02/10-ifelse 翻译
  1-js/02-first-steps/10-ifelse/1-if-zero-string/solution.md
  1-js/02-first-steps/10-ifelse/1-if-zero-string/task.md
  1-js/02-first-steps/10-ifelse/2-check-standard/solution.md
  1-js/02-first-steps/10-ifelse/2-check-standard/task.md
  1-js/02-first-steps/10-ifelse/3-sign/task.md
  1-js/02-first-steps/10-ifelse/4-check-login/solution.md
  1-js/02-first-steps/10-ifelse/4-check-login/task.md
  1-js/02-first-steps/10-ifelse/5-rewrite-if-question/task.md
  1-js/02-first-steps/10-ifelse/6-rewrite-if-else-question/task.md
  1-js/02-first-steps/10-ifelse/article.md
Labels: 正在校对

#83 1-js/06-advanced-functions/06-function-object/
  1-js/06-advanced-functions/06-function-object/2-counter-inc-dec/solution.md
  1-js/06-advanced-functions/06-function-object/2-counter-inc-dec/task.md
  1-js/06-advanced-functions/06-function-object/5-sum-many-brackets/solution.md
  1-js/06-advanced-functions/06-function-object/5-sum-many-brackets/task.md
  1-js/06-advanced-functions/06-function-object/article.md
Labels: 正在校对

#46 1-js/02-first-steps/16-javascript-specials
  1-js/02-first-steps/16-javascript-specials/article.md
Labels: 正在校对

#82 Translating 1-js/05-data-types/09-destructuring-assignment
  1-js/05-data-types/09-destructuring-assignment/1-destructuring-assignment/task.md
  1-js/05-data-types/09-destructuring-assignment/6-max-salary/task.md
  1-js/05-data-types/09-destructuring-assignment/article.md
Labels: 正在校对

#84 Translation/1 js/05 data types/03 string
  1-js/05-data-types/03-string/1-ucfirst/solution.md
  1-js/05-data-types/03-string/1-ucfirst/task.md
  1-js/05-data-types/03-string/2-check-spam/solution.md
  1-js/05-data-types/03-string/2-check-spam/task.md
  1-js/05-data-types/03-string/3-truncate/solution.md
  1-js/05-data-types/03-string/3-truncate/task.md
  1-js/05-data-types/03-string/4-extract-currency/task.md
  1-js/05-data-types/03-string/article.md
Labels: 正在校对

#86 map set weakmap weakset
  1-js/05-data-types/07-map-set-weakmap-weakset/01-array-unique-map/task.md
  1-js/05-data-types/07-map-set-weakmap-weakset/02-filter-anagrams/solution.md
  1-js/05-data-types/07-map-set-weakmap-weakset/02-filter-anagrams/task.md
  1-js/05-data-types/07-map-set-weakmap-weakset/03-iterable-keys/solution.md
  1-js/05-data-types/07-map-set-weakmap-weakset/03-iterable-keys/task.md
  1-js/05-data-types/07-map-set-weakmap-weakset/04-recipients-read/solution.md
  1-js/05-data-types/07-map-set-weakmap-weakset/04-recipients-read/task.md
  1-js/05-data-types/07-map-set-weakmap-weakset/05-recipients-when-read/solution.md
  1-js/05-data-types/07-map-set-weakmap-weakset/05-recipients-when-read/task.md
  1-js/05-data-types/07-map-set-weakmap-weakset/article.md
Labels: 翻译完成

#87 Iterables（可迭代对象）
  1-js/05-data-types/06-iterable/article.md
Labels: 正在校对

#99 1-js/06-advanced-functions/02-rest-parameters-spread-operator
  1-js/06-advanced-functions/02-rest-parameters-spread-operator/article.md
Labels: 翻译完成

#85 1-js/06-advanced-functions/01-recursion
  1-js/06-advanced-functions/01-recursion/01-sum-to/solution.md
  1-js/06-advanced-functions/01-recursion/01-sum-to/task.md
  1-js/06-advanced-functions/01-recursion/02-factorial/solution.md
  1-js/06-advanced-functions/01-recursion/02-factorial/task.md
  1-js/06-advanced-functions/01-recursion/03-fibonacci-numbers/solution.md
  1-js/06-advanced-functions/01-recursion/03-fibonacci-numbers/task.md
  1-js/06-advanced-functions/01-recursion/04-output-single-linked-list/solution.md
  1-js/06-advanced-functions/01-recursion/04-output-single-linked-list/task.md
  1-js/06-advanced-functions/01-recursion/05-output-single-linked-list-reverse/solution.md
  1-js/06-advanced-functions/01-recursion/05-output-single-linked-list-reverse/task.md
  1-js/06-advanced-functions/01-recursion/article.md
Labels: 校对认领, 正在校对

#100 Prototype
  1-js/07-object-oriented-programming/06-prototype-methods/2-dictionary-tostring/solution.md
  1-js/07-object-oriented-programming/06-prototype-methods/2-dictionary-tostring/task.md
  1-js/07-object-oriented-programming/06-prototype-methods/3-compare-calls/solution.md
  1-js/07-object-oriented-programming/06-prototype-methods/3-compare-calls/task.md
  1-js/07-object-oriented-programming/06-prototype-methods/article.md
Labels: 校对认领, 正在校对

#102 Update index.md
  1-js/index.md
Labels: 正在校对
