Repository javascript-tutorial/zh.javascript.info, pull requests merged in 2019-10, with the labels that each got.

#494 1-js/02-first-steps/02-structure/article.md
  1-js/02-first-steps/02-structure/article.md
Labels: review needed

#496 1-js/02-first-steps/03-strict-mode/article.md
  1-js/02-first-steps/03-strict-mode/article.md
Labels: review needed

#449 语句微小调整
  1-js/06-advanced-functions/03-closure/article.md
Labels: needs +1

#497 集合和范围：修正错误
  9-regular-expressions/05-regexp-character-sets-and-ranges/1-find-range-1/solution.md
Labels: needs +1

#493 修正一些翻译问题
  1-js/04-object-basics/01-object/article.md
Labels: needs +1

#498 Update 1-js/02-first-steps/04-variables
  1-js/02-first-steps/04-variables/1-hello-variables/task.md
  1-js/02-first-steps/04-variables/2-declare-variables/solution.md
  1-js/02-first-steps/04-variables/3-uppercast-constant/solution.md
  1-js/02-first-steps/04-variables/3-uppercast-constant/task.md
  1-js/02-first-steps/04-variables/article.md
Labels: changes requested

#500 update translation of 1-js/02-first-steps/05-types
  1-js/02-first-steps/05-types/1-string-quotes/solution.md
  1-js/02-first-steps/05-types/article.md
Labels: needs +1

#506 Update article.md
  2-ui/1-document/05-basic-dom-node-properties/article.md
Labels: needs +1

#507 Update task.md
  2-ui/1-document/09-size-and-scroll/1-get-scroll-height-bottom/task.md
Labels: needs +1

#504 TextDecoder and TextEncoder translate
  4-binary/02-text-decoder/article.md
Labels: needs +1

#505 Update translation of 1-js/02-first-steps/06-type-conversions
  1-js/02-first-steps/06-type-conversions/1-primitive-conversions-questions/solution.md
  1-js/02-first-steps/06-type-conversions/1-primitive-conversions-questions/task.md
  1-js/02-first-steps/06-type-conversions/article.md
Labels: needs +1

#509 docs: fix bold
  1-js/06-advanced-functions/03-closure/article.md
Labels: needs +1

#511 Eval：执行字符串内的代码
  1-js/99-js-misc/02-eval/1-eval-calculator/solution.md
  1-js/99-js-misc/02-eval/1-eval-calculator/task.md
  1-js/99-js-misc/02-eval/article.md
  1-js/99-js-misc/index.md
Labels: needs +1
