Repository javascript-tutorial/zh.javascript.info, pull requests merged in 2019-08, with the labels that each got.

#439 Update: 6-data-storage/01-cookie
  6-data-storage/01-cookie/article.md
  6-data-storage/01-cookie/cookie.js
Labels: needs +1, ready to merge

#437 Translate: 5-network/11-websocket
  5-network/08-websocket/article.md
  5-network/11-websocket/article.md
  5-network/11-websocket/chat.view/index.html
  5-network/11-websocket/chat.view/server.js
  5-network/11-websocket/demo.view/server.js
  5-network/11-websocket/websocket-handshake.svg
Labels: needs +1

#438 Translate: 5-network/12-server-sent -events
  5-network/12-server-sent-events/article.md
  5-network/12-server-sent-events/eventsource.view/index.html
  5-network/12-server-sent-events/eventsource.view/server.js
Labels: DONE

#440 Translate: 1-js/12-generators-iterators/1-generators
  1-js/12-generators-iterators/1-generators/01-pseudo-random-generator/solution.md
  1-js/12-generators-iterators/1-generators/01-pseudo-random-generator/task.md
  1-js/12-generators-iterators/1-generators/article.md
  1-js/12-generators-iterators/2-async-iterators-generators/article.md
  1-js/12-generators-iterators/2-async-iterators-generators/head.html
  1-js/12-generators-iterators/index.md
Labels: DONE

#442 Update: 1-js/02-first-steps/10-ifelse
  1-js/02-first-steps/10-ifelse/2-check-standard/task.md
  1-js/02-first-steps/10-ifelse/3-sign/task.md
  1-js/02-first-steps/10-ifelse/4-check-login/ifelse_task.svg
  1-js/02-first-steps/10-ifelse/4-check-login/solution.md
  1-js/02-first-steps/10-ifelse/4-check-login/task.md
  1-js/02-first-steps/10-ifelse/5-rewrite-if-question/solution.md
  1-js/02-first-steps/10-ifelse/5-rewrite-if-question/task.md
  1-js/02-first-steps/10-ifelse/article.md
Labels: needs +1

#443 Fix and sync upstream 1-js/05-data-types/03-string
  1-js/05-data-types/03-string/1-ucfirst/solution.md
  1-js/05-data-types/03-string/article.md
Labels: DONE

#445 Update: 1-js/02-first-steps/11-logical-operators
  1-js/02-first-steps/11-logical-operators/9-check-login/ifelse_task.svg
  1-js/02-first-steps/11-logical-operators/9-check-login/solution.md
  1-js/02-first-steps/11-logical-operators/9-check-login/task.md
  1-js/02-first-steps/11-logical-operators/article.md
Labels: needs +1

#447 Update: 1-js/02-first-steps/12-while-for
  1-js/02-first-steps/12-while-for/1-loop-last-value/solution.md
  1-js/02-first-steps/12-while-for/4-for-even/task.md
  1-js/02-first-steps/12-while-for/7-list-primes/solution.md
  1-js/02-first-steps/12-while-for/article.md
Labels: needs +1

#448 Update: 1-js/02-first-steps/13-switch
  1-js/02-first-steps/13-switch/article.md
Labels: needs +1

#446 事件循环：微任务和宏任务
  2-ui/99-ui-misc/03-event-loop/article.md
  2-ui/99-ui-misc/03-event-loop/eventLoop-full.svg
  2-ui/99-ui-misc/03-event-loop/eventLoop.svg
Labels: DONE

#451 Private and protected properties and methods
  1-js/09-classes/04-private-protected-properties-methods/article.md
Labels: needs +1

#454 update 1-js/01-getting-started/1-intro/article.md
  1-js/01-getting-started/1-intro/article.md
  1-js/01-getting-started/1-intro/limitations.svg
Labels: DONE

#455 code-style.svg
  1-js/03-code-quality/02-coding-style/code-style.svg
Labels: needs +1

#456 Translate into Chinese
  1-js/02-first-steps/10-ifelse/2-check-standard/ifelse_task2.svg
Labels: needs +1

#457 修正错别字：集成修正为继承
  1-js/04-object-basics/04-object-methods/article.md
Labels: needs +1

#458 translate Static properties and methods
  1-js/09-classes/03-static-properties-methods/article.md
Labels: needs +1

#461 修正 Infinity 拼写错误
  1-js/05-data-types/02-number/article.md
Labels: needs +1

#460 Sync: 1-js/02-first-steps/14-function-basics
  1-js/02-first-steps/14-function-basics/4-pow/solution.md
  1-js/02-first-steps/14-function-basics/article.md
  1-js/02-first-steps/14-function-basics/function_basics.png
  1-js/02-first-steps/14-function-basics/function_basics@2x.png
Labels: needs +1

#463 修正 quotes 翻译：引语 => 引号
  1-js/05-data-types/03-string/article.md
Labels: needs +1

#464 修正字符编码中对单词 back 的翻译
  1-js/05-data-types/03-string/article.md
Labels: needs +1

#465 修改 diacritical marks 的翻译为变音符号
  1-js/05-data-types/03-string/article.md
Labels: needs +1

#462 修饰翻译
  1-js/05-data-types/02-number/article.md
Labels: needs +1

#467 修改无限分数为循环小数
  1-js/05-data-types/02-number/article.md
Labels: DONE

#466 翻译 rounding 为数值修约
  1-js/05-data-types/02-number/article.md
Labels: needs +1, review needed

#468 翻译 SameValue 为同值相等
  1-js/05-data-types/02-number/article.md
Labels: needs +1
