Repository javascript-tutorial/zh.javascript.info, pull requests merged in 2019-07, with the labels that each got.

#366 Translate 1-js/09-classes/02-class-inheritance
  1-js/09-classes/02-class-inheritance/article-zh.md
  1-js/09-classes/02-class-inheritance/article.md
Labels: ready to merge

#363 Translate 2-ui/5-loading/01-onload-ondomcontentloaded and 2-ui/5-loading/03-onload-onerror
  2-ui/5-loading/01-onload-ondomcontentloaded/article.md
  2-ui/5-loading/03-onload-onerror/1-load-img-callback/solution.md
  2-ui/5-loading/03-onload-onerror/1-load-img-callback/task.md
  2-ui/5-loading/03-onload-onerror/article.md
Labels: WIP, ready to merge

#364 Translate 5 network 07 xmlhttprequest
  5-network/07-xmlhttprequest/article.md
  5-network/index.md
Labels: question, ready to merge

#368 Translate 5-network/02-fetch-progress/article.md
  5-network/02-fetch-progress/article.md
Labels: needs +1, ready to merge, 校对认领, 正在校对

#369 Translate 5-network/03-fetch-abort/article.md
  5-network/03-fetch-abort/article.md
Labels: needs +1, ready to merge, 校对认领, 正在校对

#389 Update article.md
  1-js/02-first-steps/14-function-basics/article.md
Labels: needs +1

#388 Update article.md
  1-js/02-first-steps/14-function-basics/article.md
Labels: needs +1

#391 Translate task of "mouse-events-basics".
  2-ui/3-event-details/1-mouse-events-basics/01-selectable-list/solution.view/index.html
Labels: needs +1, ready to merge

#370 Translate 5-network/04-fetch-crossorigin
  5-network/04-fetch-crossorigin/article.md
Labels: ready to merge

#394 Fix some errors (issue#393)
  2-ui/1-document/07-modifying-document/article.md
Labels: needs +1

#392 Sync 1-js/01-getting-started
  1-js/01-getting-started/1-intro/article.md
  1-js/01-getting-started/2-manuals-specifications/article.md
  1-js/01-getting-started/3-code-editors/article.md
  1-js/01-getting-started/4-devtools/article.md
  1-js/01-getting-started/4-devtools/bug.html
  1-js/01-getting-started/4-devtools/chrome.png
  1-js/01-getting-started/4-devtools/chrome@2x.png
  1-js/01-getting-started/4-devtools/safari.png
  1-js/01-getting-started/4-devtools/safari@2x.png
Labels: ready to merge

#378 custom elements
  8-web-components/2-custom-elements/1-live-timer/solution.md
  8-web-components/2-custom-elements/1-live-timer/solution.view/live-timer.js
  8-web-components/2-custom-elements/1-live-timer/source.view/index.html
  8-web-components/2-custom-elements/1-live-timer/source.view/live-timer.js
  8-web-components/2-custom-elements/1-live-timer/task.md
  8-web-components/2-custom-elements/article.md
Labels: needs +1

#377 feat: translating 08-async-await
  1-js/11-async/08-async-await/01-rewrite-async/solution.md
  1-js/11-async/08-async-await/01-rewrite-async/task.md
  1-js/11-async/08-async-await/02-rewrite-async-2/solution.md
  1-js/11-async/08-async-await/02-rewrite-async-2/task.md
  1-js/11-async/08-async-await/03-async-from-regular/solution.md
  1-js/11-async/08-async-await/03-async-from-regular/task.md
  1-js/11-async/08-async-await/article.md
Labels: needs +1

#399 1-document-11-coordinates:fix some error
  2-ui/1-document/11-coordinates/article.md
Labels: ready to merge

#396 Fix some errors and translate DocumentFragment in 2-ui/1-document/07-modifying-document
  2-ui/1-document/07-modifying-document/10-clock-setinterval/solution.view/index.html
  2-ui/1-document/07-modifying-document/10-clock-setinterval/task.md
  2-ui/1-document/07-modifying-document/7-create-object-tree/build-tree-dom.view/index.html
  2-ui/1-document/07-modifying-document/7-create-object-tree/innerhtml.view/index.html
  2-ui/1-document/07-modifying-document/7-create-object-tree/source.view/index.html
  2-ui/1-document/07-modifying-document/7-create-object-tree/task.md
  2-ui/1-document/07-modifying-document/article.md
Labels: needs +1, ready to merge

#401 Update solution.md
  1-js/05-data-types/05-array-methods/9-shuffle/solution.md
Labels: needs +1

#397 Fix some errors and sync with upstream in 1-js/11-async/03-promise-chaining
  1-js/11-async/03-promise-chaining/01-then-vs-catch/task.md
  1-js/11-async/03-promise-chaining/02-error-async/solution.md
  1-js/11-async/03-promise-chaining/02-error-async/task.md
  1-js/11-async/03-promise-chaining/article.md
  1-js/11-async/03-promise-chaining/head.html
  1-js/11-async/03-promise-chaining/promise-handler-variants-2.png
  1-js/11-async/03-promise-chaining/promise-handler-variants-2@2x.png
  1-js/11-async/03-promise-chaining/promise-handler-variants.png
  1-js/11-async/03-promise-chaining/promise-handler-variants@2x.png
  1-js/11-async/03-promise-chaining/promise-then-chain.png
  1-js/11-async/03-promise-chaining/promise-then-chain@2x.png
  1-js/11-async/03-promise-chaining/promise-then-many.png
  1-js/11-async/03-promise-chaining/promise-then-many@2x.png
Labels: needs +1

#403 1-js/11-async sync patch
  1-js/11-async/06-promisify/article.md
  1-js/11-async/07-microtask-queue/article.md
  1-js/11-async/07-microtask-queue/promiseQueue.png
  1-js/11-async/07-microtask-queue/promiseQueue@2x.png
Labels: ready to merge

#404 Update 1-js/11-async/05-promise-api
  1-js/11-async/04-promise-api/01-promise-errors-as-results/solution.md
  1-js/11-async/04-promise-api/01-promise-errors-as-results/solution.view/index.html
  1-js/11-async/04-promise-api/01-promise-errors-as-results/source.view/index.html
  1-js/11-async/04-promise-api/01-promise-errors-as-results/task.md
  1-js/11-async/04-promise-api/02-promise-errors-as-results-2/solution.md
  1-js/11-async/04-promise-api/02-promise-errors-as-results-2/solution.view/index.html
  1-js/11-async/04-promise-api/02-promise-errors-as-results-2/source.view/index.html
  1-js/11-async/04-promise-api/02-promise-errors-as-results-2/task.md
  1-js/11-async/04-promise-api/article.md
  1-js/11-async/05-promise-api/article.md
  1-js/11-async/05-promise-api/head.html
  1-js/11-async/05-promise-api/iliakan.json
  1-js/11-async/05-promise-api/one.js
  1-js/11-async/05-promise-api/two.js
Labels: needs +1, ready to merge

#405 Update 1-js/11-async/04-promise-error-handling
  1-js/11-async/04-promise-error-handling/01-error-async/solution.md
  1-js/11-async/04-promise-error-handling/01-error-async/task.md
  1-js/11-async/04-promise-error-handling/article.md
  1-js/11-async/04-promise-error-handling/getMessage.js
  1-js/11-async/04-promise-error-handling/head.html
  1-js/11-async/04-promise-error-handling/one.js
  1-js/11-async/04-promise-error-handling/promise-handler-variants-2.png
  1-js/11-async/04-promise-error-handling/promise-handler-variants-2@2x.png
  1-js/11-async/04-promise-error-handling/promise-handler-variants.png
  1-js/11-async/04-promise-error-handling/promise-handler-variants@2x.png
  1-js/11-async/04-promise-error-handling/promise-then-chain.png
  1-js/11-async/04-promise-error-handling/promise-then-chain@2x.png
  1-js/11-async/04-promise-error-handling/promise-then-many.png
  1-js/11-async/04-promise-error-handling/promise-then-many@2x.png
  1-js/11-async/04-promise-error-handling/three.js
  1-js/11-async/04-promise-error-handling/two.js
  1-js/11-async/04-promise-error-handling/user.json
Labels: needs +1, ready to merge

#407 feat:add pr template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: needs +1

#406 Translate 6-data-storage/02-localstorage/article.md
  6-data-storage/02-localstorage/1-form-autosave/task.md
  6-data-storage/02-localstorage/article.md
Labels: needs +1, ready to merge

#409 remove 05-async-await
  1-js/11-async/05-async-await/01-rewrite-async-2/solution.md
  1-js/11-async/05-async-await/01-rewrite-async-2/task.md
  1-js/11-async/05-async-await/01-rewrite-async/solution.md
  1-js/11-async/05-async-await/01-rewrite-async/task.md
  1-js/11-async/05-async-await/article.md
  1-js/11-async/05-async-await/head.html
Labels: ready to merge

#412 Update: 1-js/02-first-steps/02-structure
  1-js/02-first-steps/02-structure/article.md
Labels: needs +1

#410 Update 1-js/02-first-steps/01-hello-world
  1-js/02-first-steps/01-hello-world/1-hello-alert/task.md
  1-js/02-first-steps/01-hello-world/2-hello-alert-ext/task.md
  1-js/02-first-steps/01-hello-world/article.md
Labels: needs +1

#420 Update: 1-js/02-first-steps/03-strict-mode
  1-js/02-first-steps/03-strict-mode/article.md
Labels: needs +1

#421 Update: 1-js/02-first-steps/04-variables
  1-js/02-first-steps/04-variables/article.md
Labels: DONE, needs +1

#414 Update: 5-network/01-fetch
  5-network/01-fetch/01-fetch-users/_js.view/solution.js
  5-network/01-fetch/01-fetch-users/_js.view/source.js
  5-network/01-fetch/01-fetch-users/_js.view/test.js
  5-network/01-fetch/01-fetch-users/solution.md
  5-network/01-fetch/01-fetch-users/task.md
  5-network/01-fetch/article.md
  5-network/01-fetch/logo-fetch.svg
  5-network/01-fetch/post.view/server.js
Labels: ready to merge

#415 Update: 5-network/02-formdata
  5-network/02-formdata/article.md
  5-network/02-formdata/post.view/server.js
Labels: ready to merge

#416 Update: 5-network/03-fetch-progress
  5-network/03-fetch-progress/article.md
  5-network/03-fetch-progress/logo-fetch.svg
  5-network/03-fetch-progress/progress.view/index.html
  5-network/03-fetch-progress/progress.view/long.txt
Labels: ready to merge

#417 Update: 5-network/04-fetch-abort
  5-network/04-fetch-abort/article.md
  5-network/04-fetch-abort/demo.view/server.js
Labels: ready to merge

#419 Update: 5-network/06-fetch-api
  5-network/06-fetch-api/article.md
  5-network/06-fetch-api/logo-fetch.svg
  5-network/06-fetch-api/post.view/index.html
  5-network/06-fetch-api/post.view/server.js
Labels: needs +1

#408 Translate 8-web-components/7-shadow-dom-events/article.md
  8-web-components/7-shadow-dom-events/article.md
Labels: needs +1, ready to merge

#424 update pr template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: needs +1

#418 Update: 5-network/05-fetch-crossorigin
  5-network/04-fetch-crossorigin/cors-gmail-messages.png
  5-network/04-fetch-crossorigin/cors-gmail-messages@2x.png
  5-network/05-fetch-crossorigin/1-do-we-need-origin/solution.md
  5-network/05-fetch-crossorigin/1-do-we-need-origin/task.md
  5-network/05-fetch-crossorigin/article.md
  5-network/05-fetch-crossorigin/cors-gmail-messages.png
  5-network/05-fetch-crossorigin/cors-gmail-messages@2x.png
  5-network/05-fetch-crossorigin/demo.view/index.html
  5-network/05-fetch-crossorigin/demo.view/server.js
  5-network/05-fetch-crossorigin/xhr-another-domain.png
  5-network/05-fetch-crossorigin/xhr-another-domain@2x.png
  5-network/05-fetch-crossorigin/xhr-preflight.png
  5-network/05-fetch-crossorigin/xhr-preflight@2x.png
Labels: needs +1

#426 Update: 1-js/02-first-steps/06-type-conversions
  1-js/02-first-steps/06-type-conversions/article.md
Labels: needs +1

#425 Update: 5-network-07-url
  5-network/06-url/article.md
  5-network/06-url/url-object.png
  5-network/06-url/url-object@2x.png
  5-network/07-url/article.md
  5-network/07-url/url-object.png
  5-network/07-url/url-object@2x.png
Labels: needs +1, 正在校对

#428 Update: 1-js/02-first-steps/07-operators
  1-js/02-first-steps/07-operators/article.md
Labels: ready to merge

#422 Translate web component shadow dom
  8-web-components/3-shadow-dom/article.md
Labels: needs +1

#427 Update: 5-network/08-xmlhttprequest
  5-network/08-xmlhttprequest/article.md
  5-network/08-xmlhttprequest/example.view/index.html
  5-network/08-xmlhttprequest/example.view/server.js
  5-network/08-xmlhttprequest/hello.txt
  5-network/08-xmlhttprequest/phones-async.view/index.html
  5-network/08-xmlhttprequest/phones-async.view/phones.json
  5-network/08-xmlhttprequest/phones-async.view/server.js
  5-network/08-xmlhttprequest/phones.json
  5-network/08-xmlhttprequest/phones.view/index.html
  5-network/08-xmlhttprequest/phones.view/phones.json
  5-network/08-xmlhttprequest/phones.view/server.js
  5-network/08-xmlhttprequest/post.view/index.html
  5-network/08-xmlhttprequest/post.view/server.js
Labels: DONE

#431 Update: 1-js/02-first-steps/08-comparison
  1-js/02-first-steps/08-comparison/1-comparison-questions/solution.md
  1-js/02-first-steps/08-comparison/article.md
Labels: needs +1, review needed

#429 Translate: 5-network/09-resume-upload
  5-network/09-resume-upload/article.md
  5-network/09-resume-upload/upload-resume.view/index.html
  5-network/09-resume-upload/upload-resume.view/server.js
  5-network/09-resume-upload/upload-resume.view/uploader.js
Labels: DONE

#430 Translate: 5-network-10-long-polling
  5-network/10-long-polling/article.md
  5-network/10-long-polling/long-polling.png
  5-network/10-long-polling/long-polling@2x.png
  5-network/10-long-polling/longpoll.view/browser.js
  5-network/10-long-polling/longpoll.view/index.html
  5-network/10-long-polling/longpoll.view/server.js
Labels: DONE

#433 Update: 1-js/02-first-steps/09-alert-prompt-confirm
  1-js/02-first-steps/09-alert-prompt-confirm/article.md
Labels: needs +1

#435 Translate 6-data-storage/01-cookie/article.md
  6-data-storage/01-cookie/article.md
Labels: needs +1
