Repository javascript-tutorial/zh.javascript.info, pull requests merged in 2019-11, with the labels that each got.

#508 Update translation of 1-js/02-first-steps/07-operators
  1-js/02-first-steps/07-operators/1-increment-order/solution.md
  1-js/02-first-steps/07-operators/2-assignment-result/solution.md
  1-js/02-first-steps/07-operators/2-assignment-result/task.md
  1-js/02-first-steps/07-operators/article.md
Labels: needs +1

#512 File and FileReader
  4-binary/04-file/article.md
Labels: needs +1

#514 Update 1-js/02-first-steps/08-comparison
  1-js/02-first-steps/08-comparison/1-comparison-questions/solution.md
  1-js/02-first-steps/08-comparison/article.md
Labels: needs +1

#516 Update translation of 1-js/02-first-steps/09-alert-prompt-confirm
  1-js/02-first-steps/09-alert-prompt-confirm/1-simple-page/task.md
  1-js/02-first-steps/09-alert-prompt-confirm/article.md
Labels: DONE, needs +1

#517 Update translation of 1-js/02-first-steps/10-ifelse
  1-js/02-first-steps/10-ifelse/1-if-zero-string/solution.md
  1-js/02-first-steps/10-ifelse/1-if-zero-string/task.md
  1-js/02-first-steps/10-ifelse/2-check-standard/ifelse_task2.svg
  1-js/02-first-steps/10-ifelse/2-check-standard/solution.md
  1-js/02-first-steps/10-ifelse/3-sign/task.md
  1-js/02-first-steps/10-ifelse/article.md
Labels: needs +1, 正在校对

#519 blob
  4-binary/03-blob/article.md
Labels: needs +1

#524 Update translation of 1-js/02-first-steps/13-switch
  1-js/02-first-steps/13-switch/1-rewrite-switch-if-else/solution.md
  1-js/02-first-steps/13-switch/1-rewrite-switch-if-else/task.md
  1-js/02-first-steps/13-switch/2-rewrite-if-switch/solution.md
  1-js/02-first-steps/13-switch/2-rewrite-if-switch/task.md
  1-js/02-first-steps/13-switch/article.md
Labels: needs +1

#477 修改翻译错误
  1-js/11-async/02-promise-basics/article.md
Labels: needs +1

#520 Update translation of 1-js/02-first-steps/11-logical-operators
  1-js/02-first-steps/11-logical-operators/2-alert-or/solution.md
  1-js/02-first-steps/11-logical-operators/4-alert-and/solution.md
  1-js/02-first-steps/11-logical-operators/6-check-if-in-range/task.md
  1-js/02-first-steps/11-logical-operators/article.md
Labels: changes requested

#521 Update the translation of 1-js/02-first-steps/12-while-for
  1-js/02-first-steps/12-while-for/1-loop-last-value/solution.md
  1-js/02-first-steps/12-while-for/2-which-value-while/solution.md
  1-js/02-first-steps/12-while-for/2-which-value-while/task.md
  1-js/02-first-steps/12-while-for/3-which-value-for/solution.md
  1-js/02-first-steps/12-while-for/4-for-even/task.md
  1-js/02-first-steps/12-while-for/6-repeat-until-correct/solution.md
  1-js/02-first-steps/12-while-for/6-repeat-until-correct/task.md
  1-js/02-first-steps/12-while-for/7-list-primes/solution.md
  1-js/02-first-steps/12-while-for/7-list-primes/task.md
  1-js/02-first-steps/12-while-for/article.md
Labels: changes requested

#518 async-iterators-generators
  1-js/12-generators-iterators/2-async-iterators-generators/article.md
  1-js/12-generators-iterators/2-async-iterators-generators/head.html
Labels: changes requested, needs +1

#534 Update 01-05-08
  1-js/05-data-types/08-weakmap-weakset/01-recipients-read/solution.md
  1-js/05-data-types/08-weakmap-weakset/01-recipients-read/task.md
  1-js/05-data-types/08-weakmap-weakset/02-recipients-when-read/solution.md
  1-js/05-data-types/08-weakmap-weakset/02-recipients-when-read/task.md
Labels: review needed

#536 Fix: type error of 1-js/05-data-types/10-destructuring-assignment/article.md
  1-js/05-data-types/10-destructuring-assignment/article.md
Labels: needs +1

#531 05-extends-natives
  1-js/09-classes/05-extend-natives/article.md
Labels: needs +1, review needed

#538 minor change: revert // 程序错误提示 (非注释）to english
  1-js/09-classes/05-extend-natives/article.md
Labels: needs +1

#537 Arrow functions, the basics
  1-js/02-first-steps/16-arrow-functions-basics/article.md
Labels: needs +1

#535 Update translation of 1-js/02-first-steps/15-function-expressions
  1-js/02-first-steps/15-function-expressions/article.md
Labels: needs +1

#542 Update the translation of 1-js/02-first-steps/17-javascript-specials
  1-js/02-first-steps/17-javascript-specials/article.md
Labels: changes requested
