Repository javascript-tutorial/zh.javascript.info, pull requests merged in 2019-09, with the labels that each got.

#472 修正中文语法问题
  1-js/04-object-basics/04-object-methods/article.md
Labels: needs +1

#473 Update article.md
  1-js/08-prototypes/01-prototype-inheritance/article.md
Labels: needs +1

#476 修复格式错误
  1-js/08-prototypes/03-native-prototypes/article.md
Labels: needs +1

#475 Update article.md
  1-js/08-prototypes/02-function-prototype/article.md
Labels: needs +1

#469 Update: 1-js/02-first-steps/15-function-expressions-arrows
  1-js/02-first-steps/15-function-expressions-arrows/article.md
Labels: needs +1

#485 修正272行单词拼写错误
  1-js/05-data-types/02-number/article.md
Labels: needs +1

#479 1-js/01-getting-started/2-manuals-specifications/article.md
  1-js/01-getting-started/2-manuals-specifications/article.md
Labels: needs +1

#481 update 1-js / 01-getting-started / 3-code-editors
  1-js/01-getting-started/3-code-editors/article.md
Labels: needs +1

#487 Fix typo
  1-js/05-data-types/03-string/article.md
Labels: DONE

#486 Update: 1-js/02-first-steps/16-javascript-specials
  1-js/02-first-steps/16-javascript-specials/article.md
Labels: needs +1

#474 Fix: 1-js/08-prototypes/01-prototype-inheritance
  1-js/08-prototypes/01-prototype-inheritance/article.md
Labels: DONE, needs +1

#484 Update 1-js/02-first-steps/01-hello-world
  1-js/02-first-steps/01-hello-world/article.md
Labels: needs +1

#489 修改一处有关Promise.allSettled的错误
  1-js/11-async/05-promise-api/article.md
Labels: needs +1
