Repository javascript-tutorial/zh.javascript.info, pull requests merged in 2019-06, with the labels that each got.

#348 Fix some typo and improve translation
  1-js/01-getting-started/1-intro/article.md
  1-js/02-first-steps/16-javascript-specials/article.md
  1-js/03-code-quality/02-coding-style/article.md
  1-js/03-code-quality/03-comments/article.md
  1-js/04-object-basics/01-object/article.md
  1-js/04-object-basics/05-object-toprimitive/article.md
  1-js/05-data-types/02-number/article.md
  1-js/05-data-types/03-string/article.md
  1-js/05-data-types/04-array/article.md
  1-js/05-data-types/05-array-methods/article.md
  1-js/05-data-types/07-map-set-weakmap-weakset/article.md
  1-js/05-data-types/08-keys-values-entries/article.md
  1-js/06-advanced-functions/01-recursion/article.md
  1-js/07-object-oriented-programming/10-class-inheritance/animal-rabbit-extends.png
  2-ui/1-document/02-dom-nodes/article.md
  2-ui/1-document/04-searching-elements-dom/article.md
  2-ui/1-document/07-modifying-document/article.md
  2-ui/1-document/09-size-and-scroll/article.md
Labels: needs +1, question

#343 Unicode character properties \p
  9-regular-expressions/21-regexp-unicode-properties/article.md
Labels: needs +1, 校对认领

#342 和英文版同步
  1-js/05-data-types/01-primitives-methods/article.md
Labels: needs +1, 校对认领

#349 Translate 1-js/13-modules/01-modules-intro/article.md
  1-js/13-modules/01-modules-intro/article.md
  1-js/13-modules/01-modules-intro/say.view/index.html
  1-js/13-modules/01-modules-intro/say.view/say.js
  1-js/13-modules/01-modules-intro/scopes-working.view/hello.js
  1-js/13-modules/01-modules-intro/scopes-working.view/index.html
  1-js/13-modules/01-modules-intro/scopes-working.view/user.js
  1-js/13-modules/01-modules-intro/scopes.view/hello.js
  1-js/13-modules/01-modules-intro/scopes.view/index.html
  1-js/13-modules/01-modules-intro/scopes.view/user.js
Labels: needs +1, ready to merge

#350 Translated README.MD.
  README.md
Labels: WIP, enhancement, needs +1

#341 翻译章节“前瞻与后瞻断言”
  9-regular-expressions/14-regexp-lookahead-lookbehind/article.md
Labels: WIP, enhancement, needs +1

#358 缺少 toString
  1-js/07-object-oriented-programming/06-prototype-methods/2-dictionary-tostring/solution.md
Labels: review needed

#360 Make the description more readable.
  1-js/02-first-steps/06-type-conversions/article.md
Labels: needs +1

#351 Translate 1-js/13-modules/02-import-export & 1-js/13-modules/03-modules-dynamic-imports
  1-js/13-modules/02-import-export/article.md
  1-js/13-modules/03-modules-dynamic-imports/article.md
  1-js/13-modules/03-modules-dynamic-imports/say.view/index.html
  1-js/13-modules/03-modules-dynamic-imports/say.view/say.js
  1-js/13-modules/index.md
Labels: needs +1, ready to merge

#361 Translate 2-ui/5-loading/02-script-async-defer/article.md
  2-ui/5-loading/02-script-async-defer/article.md
  2-ui/5-loading/02-script-async-defer/long.js
  2-ui/5-loading/02-script-async-defer/small.js
  2-ui/5-loading/index.md
Labels: DONE

#359 Microtasks and event loop
  6-async/07-microtask-queue/article.md
  6-async/07-microtask-queue/eventLoop.png
  6-async/07-microtask-queue/eventLoop@2x.png
  6-async/07-microtask-queue/promiseQueue.png
  6-async/07-microtask-queue/promiseQueue@2x.png
Labels: needs +1, ready to merge

#374 Fix typo 13-modules/01-modules-intro
  1-js/13-modules/01-modules-intro/article.md
Labels: needs +1

#373 Translate 5-network/06-url/article.md
  5-network/06-url/article.md
Labels: WIP, needs +1, ready to merge

#371 From the orbital height
  8-web-components/1-webcomponents-intro/article.md
Labels: needs +1, ready to merge, 正在校对

#365 Translate 1-js/09-classes/01-class
  1-js/09-classes/01-class/1-rewrite-to-class/task.md
  1-js/09-classes/01-class/article.md
Labels: ready to merge, 校对认领, 正在校对

#367 Translate 5-network/01-fetch-basics/article.md
  5-network/01-fetch-basics/article.md
Labels: needs +1, ready to merge, 正在校对

#375 修正笔误
  1-js/11-async/02-promise-basics/article.md
Labels: needs +1

#379 Fix error
  9-regular-expressions/07-regexp-quantifiers/article.md
Labels: needs +1

#380 翻译优化建议。
  1-js/02-first-steps/04-variables/article.md
Labels: WIP, needs +1

#382 修正翻译错误
  2-ui/3-event-details/4-mouse-drag-and-drop/article.md
Labels: needs +1

#381 feat(section-1.5.5.8): update task and solution
  1-js/05-data-types/05-array-methods/8-sort-objects/solution.md
  1-js/05-data-types/05-array-methods/8-sort-objects/task.md
Labels: needs +1

#383 修改一处markdown的排版问题；以及一个翻译建议。
  1-js/02-first-steps/12-while-for/2-which-value-while/solution.md
Labels: needs +1
