Repository javascript-tutorial/zh.javascript.info, pull requests merged in 2019-12, with the labels that each got.

#539 Update 1-js/03-code-quality/01-debugging-chrome
  1-js/03-code-quality/01-debugging-chrome/article.md
Labels: needs +1

#529 ArrayBuffer, binary arrays
  4-binary/01-arraybuffer-binary-arrays/01-concat/_js.view/solution.js
  4-binary/01-arraybuffer-binary-arrays/01-concat/_js.view/source.js
  4-binary/01-arraybuffer-binary-arrays/01-concat/task.md
  4-binary/01-arraybuffer-binary-arrays/article.md
Labels: needs +1

#546 Update 1-03-01
  1-js/03-code-quality/01-debugging-chrome/chrome-open-sources.svg
  1-js/03-code-quality/01-debugging-chrome/chrome-sources-breakpoint.svg
  1-js/03-code-quality/01-debugging-chrome/chrome-sources-console.svg
  1-js/03-code-quality/01-debugging-chrome/chrome-sources-debugger-pause.svg
  1-js/03-code-quality/01-debugging-chrome/chrome-sources-debugger-trace-1.svg
  1-js/03-code-quality/01-debugging-chrome/chrome-tabs.svg
  1-js/03-code-quality/01-debugging-chrome/head.html
  1-js/03-code-quality/01-debugging-chrome/largeIcons.svg
  1-js/03-code-quality/01-debugging-chrome/toolbarButtonGlyphs.svg
Labels: review needed

#543 5-network/06-fetch-api
  5-network/06-fetch-api/article.md
Labels: needs +1

#547 4-binary/01-arraybuffer-binary-arrays/ sync with en
  4-binary/01-arraybuffer-binary-arrays/8bit-integer-256.svg
  4-binary/01-arraybuffer-binary-arrays/8bit-integer-257.svg
  4-binary/01-arraybuffer-binary-arrays/arraybuffer-view-buffersource.svg
  4-binary/01-arraybuffer-binary-arrays/arraybuffer-views.svg
  4-binary/01-arraybuffer-binary-arrays/article.md
Labels: needs +1

#549 Big int
  1-js/99-js-misc/05-bigint/article.md
Labels: needs +1

#555 [fix]5-network/06-fetch-api
  5-network/06-fetch-api/article.md
Labels: needs +1

#556 Update translation of 1-js/03-code-quality/04-ninja-code
  1-js/03-code-quality/04-ninja-code/article.md
Labels: changes requested

#552 Update translation of 1-js/03-code-quality/03-comments
  1-js/03-code-quality/03-comments/article.md
Labels: DONE

#544 2-ui/99-ui-misc/01-mutation-observer/
  2-ui/99-ui-misc/01-mutation-observer/article.md
Labels: changes requested

#560 Update article.md
  1-js/11-async/04-promise-error-handling/article.md
Labels: needs +1

#548 Update Translation of 1-js/03-code-quality/02-coding-style
  1-js/03-code-quality/02-coding-style/1-style-errors/solution.md
  1-js/03-code-quality/02-coding-style/article.md
  1-js/03-code-quality/02-coding-style/code-style.svg
  1-js/03-code-quality/02-coding-style/figure-bracket-style.png
  1-js/03-code-quality/02-coding-style/figure-bracket-style@2x.png
Labels: needs +1

#563 Update translation of 1-js/03-code-quality/06-polyfills/article.md
  1-js/03-code-quality/06-polyfills/article.md
Labels: changes requested

#558 Update files of 1-js/03-code-quality/05-testing-mocha
  1-js/03-code-quality/05-testing-mocha/3-pow-test-wrong/solution.md
  1-js/03-code-quality/05-testing-mocha/3-pow-test-wrong/task.md
  1-js/03-code-quality/05-testing-mocha/article.md
  1-js/03-code-quality/05-testing-mocha/pow-2.view/index.html
  1-js/03-code-quality/05-testing-mocha/pow-4.view/test.js
  1-js/03-code-quality/05-testing-mocha/pow-full.view/test.js
  1-js/03-code-quality/05-testing-mocha/pow-nan.view/test.js
Labels: changes requested, 正在校对

#568 同步上游和修改标题
  1-js/05-data-types/07-map-set/02-filter-anagrams/solution.md
  1-js/05-data-types/07-map-set/article.md
  1-js/05-data-types/08-weakmap-weakset/02-recipients-when-read/solution.md
  1-js/05-data-types/08-weakmap-weakset/article.md
Labels: needs +1

#557 Update task.md
  1-js/06-advanced-functions/09-call-apply-decorators/03-debounce/task.md
Labels: needs +1

#551 2-ui/99-ui-misc/02-selection-range/
  2-ui/99-ui-misc/02-selection-range/article.md
Labels: DONE

#565 9-regular-expressions/06-regexp-boundary/
  9-regular-expressions/06-regexp-boundary/1-find-time-hh-mm/solution.md
  9-regular-expressions/06-regexp-boundary/article.md
Labels: DONE

#564 Update translation of 1-js/04-object-basics/01-object/article.md
  1-js/04-object-basics/01-object/2-hello-object/task.md
  1-js/04-object-basics/01-object/3-is-empty/solution.md
  1-js/04-object-basics/01-object/3-is-empty/task.md
  1-js/04-object-basics/01-object/4-const-object/solution.md
  1-js/04-object-basics/01-object/4-const-object/task.md
  1-js/04-object-basics/01-object/5-sum-object/solution.md
  1-js/04-object-basics/01-object/5-sum-object/task.md
  1-js/04-object-basics/01-object/8-multiply-numeric/task.md
  1-js/04-object-basics/01-object/article.md
  1-js/04-object-basics/01-object/object-user-delete.svg
  1-js/04-object-basics/01-object/object-user-empty.svg
  1-js/04-object-basics/01-object/object-user-isadmin.svg
  1-js/04-object-basics/01-object/object-user-props.svg
  1-js/04-object-basics/01-object/object-user.svg
  1-js/04-object-basics/01-object/object.svg
  1-js/04-object-basics/01-object/variable-contains-reference.svg
  1-js/04-object-basics/01-object/variable-copy-reference.svg
  1-js/04-object-basics/01-object/variable-copy-value.svg
Labels: needs +1

#561 translate 1-js/99-js-misc/01-proxy/article.md
  1-js/99-js-misc/01-proxy/01-error-nonexisting/task.md
  1-js/99-js-misc/01-proxy/02-array-negative/task.md
  1-js/99-js-misc/01-proxy/03-observable/solution.md
  1-js/99-js-misc/01-proxy/03-observable/task.md
  1-js/99-js-misc/01-proxy/article.md
Labels: needs +1, 正在校对

#570 Update translation of 1-js/04-object-basics/02-garbage-collection
  1-js/04-object-basics/02-garbage-collection/article.md
  1-js/04-object-basics/02-garbage-collection/family-delete-refs.svg
  1-js/04-object-basics/02-garbage-collection/family-no-family.svg
  1-js/04-object-basics/02-garbage-collection/family-no-father-2.svg
  1-js/04-object-basics/02-garbage-collection/family-no-father.svg
  1-js/04-object-basics/02-garbage-collection/family.svg
  1-js/04-object-basics/02-garbage-collection/garbage-collection-1.svg
  1-js/04-object-basics/02-garbage-collection/garbage-collection-2.svg
  1-js/04-object-basics/02-garbage-collection/garbage-collection-3.svg
  1-js/04-object-basics/02-garbage-collection/garbage-collection-4.svg
  1-js/04-object-basics/02-garbage-collection/garbage-collection-5.svg
  1-js/04-object-basics/02-garbage-collection/memory-user-john-admin.svg
  1-js/04-object-basics/02-garbage-collection/memory-user-john-lost.svg
  1-js/04-object-basics/02-garbage-collection/memory-user-john.svg
Labels: needs +1
