Repository javascript-tutorial/zh.javascript.info, pull requests merged in 2020-03, with the labels that each got.

#625 1-js/06-advanced-functions/09-call-apply-decorators
  1-js/06-advanced-functions/09-call-apply-decorators/01-spy-decorator/_js.view/solution.js
  1-js/06-advanced-functions/09-call-apply-decorators/01-spy-decorator/solution.md
  1-js/06-advanced-functions/09-call-apply-decorators/01-spy-decorator/task.md
  1-js/06-advanced-functions/09-call-apply-decorators/02-delay/solution.md
  1-js/06-advanced-functions/09-call-apply-decorators/02-delay/task.md
  1-js/06-advanced-functions/09-call-apply-decorators/03-debounce/_js.view/test.js
  1-js/06-advanced-functions/09-call-apply-decorators/03-debounce/solution.md
  1-js/06-advanced-functions/09-call-apply-decorators/03-debounce/task.md
  1-js/06-advanced-functions/09-call-apply-decorators/04-throttle/_js.view/test.js
  1-js/06-advanced-functions/09-call-apply-decorators/04-throttle/solution.md
  1-js/06-advanced-functions/09-call-apply-decorators/04-throttle/task.md
  1-js/06-advanced-functions/09-call-apply-decorators/article.md
  1-js/06-advanced-functions/09-call-apply-decorators/decorator-makecaching-wrapper.svg
Labels: review needed

#626 Update translation of 1-js/06-advanced-functions/10-bind
  1-js/06-advanced-functions/10-bind/3-second-bind/solution.md
  1-js/06-advanced-functions/10-bind/3-second-bind/task.md
  1-js/06-advanced-functions/10-bind/4-function-property-after-bind/solution.md
  1-js/06-advanced-functions/10-bind/4-function-property-after-bind/task.md
  1-js/06-advanced-functions/10-bind/5-question-use-bind/solution.md
  1-js/06-advanced-functions/10-bind/5-question-use-bind/task.md
  1-js/06-advanced-functions/10-bind/6-ask-partial/solution.md
  1-js/06-advanced-functions/10-bind/6-ask-partial/task.md
  1-js/06-advanced-functions/10-bind/article.md
Labels: review needed

#629 Update translation of 1-js/07-object-properties/01-property-descriptors
  1-js/07-object-properties/01-property-descriptors/article.md
Labels: review needed

#630 Update translation of 1-js/07-object-properties/02-property-accessors
  1-js/07-object-properties/02-property-accessors/article.md
Labels: review needed

#632 Update translation of 1-js/08-prototypes/01-prototype-inheritance
  1-js/08-prototypes/01-prototype-inheritance/1-property-after-delete/solution.md
  1-js/08-prototypes/01-prototype-inheritance/1-property-after-delete/task.md
  1-js/08-prototypes/01-prototype-inheritance/2-search-algorithm/solution.md
  1-js/08-prototypes/01-prototype-inheritance/2-search-algorithm/task.md
  1-js/08-prototypes/01-prototype-inheritance/3-proto-and-this/solution.md
  1-js/08-prototypes/01-prototype-inheritance/3-proto-and-this/task.md
  1-js/08-prototypes/01-prototype-inheritance/4-hamster-proto/solution.md
  1-js/08-prototypes/01-prototype-inheritance/4-hamster-proto/task.md
  1-js/08-prototypes/01-prototype-inheritance/article.md
  1-js/08-prototypes/01-prototype-inheritance/object-prototype-empty.svg
  1-js/08-prototypes/01-prototype-inheritance/proto-animal-rabbit-chain.svg
  1-js/08-prototypes/01-prototype-inheritance/proto-animal-rabbit-walk-2.svg
  1-js/08-prototypes/01-prototype-inheritance/proto-animal-rabbit-walk-3.svg
  1-js/08-prototypes/01-prototype-inheritance/proto-animal-rabbit-walk.svg
  1-js/08-prototypes/01-prototype-inheritance/proto-animal-rabbit.svg
  1-js/08-prototypes/01-prototype-inheritance/proto-user-admin.svg
  1-js/08-prototypes/01-prototype-inheritance/rabbit-animal-object.svg
Labels: review needed

#633 Update translation of 1-js/08-prototypes/02-function-prototype
  1-js/08-prototypes/02-function-prototype/1-changing-prototype/solution.md
  1-js/08-prototypes/02-function-prototype/1-changing-prototype/task.md
  1-js/08-prototypes/02-function-prototype/4-new-object-same-constructor/solution.md
  1-js/08-prototypes/02-function-prototype/4-new-object-same-constructor/task.md
  1-js/08-prototypes/02-function-prototype/article.md
  1-js/08-prototypes/02-function-prototype/function-prototype-constructor.svg
  1-js/08-prototypes/02-function-prototype/native-prototypes-array-tostring.svg
  1-js/08-prototypes/02-function-prototype/native-prototypes-classes.svg
  1-js/08-prototypes/02-function-prototype/object-prototype-1.svg
  1-js/08-prototypes/02-function-prototype/object-prototype.svg
  1-js/08-prototypes/02-function-prototype/proto-constructor-animal-rabbit.svg
  1-js/08-prototypes/02-function-prototype/rabbit-animal-object.svg
  1-js/08-prototypes/02-function-prototype/rabbit-prototype-constructor.svg
Labels: review needed

#634 Update svg and png files of 1-js/08-prototypes
  1-js/08-prototypes/03-native-prototypes/function-prototype-constructor.svg
  1-js/08-prototypes/03-native-prototypes/native-prototypes-array-tostring.svg
  1-js/08-prototypes/03-native-prototypes/native-prototypes-classes.svg
  1-js/08-prototypes/03-native-prototypes/object-prototype-1.svg
  1-js/08-prototypes/03-native-prototypes/object-prototype-null.svg
  1-js/08-prototypes/03-native-prototypes/object-prototype.svg
  1-js/08-prototypes/03-native-prototypes/proto-constructor-animal-rabbit.svg
  1-js/08-prototypes/03-native-prototypes/rabbit-prototype-constructor.svg
  1-js/08-prototypes/04-prototype-methods/object-prototype-2.svg
  1-js/08-prototypes/04-prototype-methods/object-prototype-null.svg
  1-js/08-prototypes/04-prototype-methods/rabbit-animal-object.svg
Labels: review needed

#635 Update translation of 1-js/08-prototypes/03-native-prototypes
  1-js/08-prototypes/03-native-prototypes/1-defer-to-prototype/task.md
  1-js/08-prototypes/03-native-prototypes/2-defer-to-prototype-extended/solution.md
  1-js/08-prototypes/03-native-prototypes/2-defer-to-prototype-extended/task.md
  1-js/08-prototypes/03-native-prototypes/article.md
Labels: review needed

#636 Update translation of 1-js/08-prototypes/04-prototype-methods
  1-js/08-prototypes/04-prototype-methods/2-dictionary-tostring/solution.md
  1-js/08-prototypes/04-prototype-methods/2-dictionary-tostring/task.md
  1-js/08-prototypes/04-prototype-methods/3-compare-calls/solution.md
  1-js/08-prototypes/04-prototype-methods/3-compare-calls/task.md
  1-js/08-prototypes/04-prototype-methods/article.md
Labels: review needed

#628 update "1-js/12-generators-iterators/1-generators"
  1-js/12-generators-iterators/1-generators/article.md
Labels: DONE

#637 Update translation of 1-js/09-classes/01-class
  1-js/09-classes/01-class/1-rewrite-to-class/task.md
  1-js/09-classes/01-class/article.md
  1-js/09-classes/01-class/class-user.svg
Labels: review needed

#639 Update translation of 1-js/09-classes/02-class-inheritance
  1-js/09-classes/02-class-inheritance/1-class-constructor-error/solution.md
  1-js/09-classes/02-class-inheritance/2-clock-class-extended/solution.md
  1-js/09-classes/02-class-inheritance/2-clock-class-extended/task.md
  1-js/09-classes/02-class-inheritance/3-class-extend-object/solution.md
  1-js/09-classes/02-class-inheritance/3-class-extend-object/task.md
  1-js/09-classes/02-class-inheritance/article.md
Labels: review needed

#640 Update translation of 1-js/09-classes/04-private-protected-properties-methods
  1-js/09-classes/04-private-protected-properties-methods/article.md
Labels: review needed

#641 Update translation of 1-js/09-classes/05-extend-natives
  1-js/09-classes/05-extend-natives/article.md
Labels: review needed

#642 Update translation of 1-js/09-classes/06-instanceof
  1-js/09-classes/06-instanceof/1-strange-instanceof/solution.md
  1-js/09-classes/06-instanceof/1-strange-instanceof/task.md
  1-js/09-classes/06-instanceof/article.md
Labels: review needed

#643 Update translation of 1-js/09-classes/07-mixins
  1-js/09-classes/07-mixins/article.md
Labels: review needed

#644 Update translation of 1-js/10-error-handling/1-try-catch
  1-js/10-error-handling/1-try-catch/1-finally-or-code-after/solution.md
  1-js/10-error-handling/1-try-catch/1-finally-or-code-after/task.md
  1-js/10-error-handling/1-try-catch/article.md
Labels: review needed

#646 Update translation of 1-js/10-error-handling/2-custom-errors
  1-js/10-error-handling/2-custom-errors/1-format-error/solution.md
  1-js/10-error-handling/2-custom-errors/1-format-error/task.md
  1-js/10-error-handling/2-custom-errors/article.md
Labels: review needed

#647 Update svg etc. files in 1-js
  1-js/11-async/01-callbacks/callback-hell.svg
  1-js/11-async/02-promise-basics/promise-reject-1.svg
  1-js/11-async/02-promise-basics/promise-resolve-1.svg
  1-js/11-async/02-promise-basics/promise-resolve-reject.svg
  1-js/11-async/03-promise-chaining/promise-handler-variants.svg
  1-js/11-async/03-promise-chaining/promise-then-chain.svg
  1-js/11-async/03-promise-chaining/promise-then-many.svg
  1-js/11-async/04-promise-error-handling/promise-handler-variants.svg
  1-js/11-async/04-promise-error-handling/promise-then-chain.svg
  1-js/11-async/04-promise-error-handling/promise-then-many.svg
  1-js/12-generators-iterators/1-generators/genYield2-2.svg
  1-js/12-generators-iterators/1-generators/genYield2.svg
  1-js/12-generators-iterators/1-generators/generateSequence-1.svg
  1-js/12-generators-iterators/1-generators/generateSequence-2.svg
  1-js/12-generators-iterators/1-generators/generateSequence-3.svg
  1-js/12-generators-iterators/1-generators/generateSequence-4.svg
  1-js/13-modules/01-modules-intro/say.view/index.html
  1-js/13-modules/01-modules-intro/say.view/say.js
  1-js/13-modules/01-modules-intro/scopes-working.view/hello.js
  1-js/13-modules/01-modules-intro/scopes-working.view/index.html
  1-js/13-modules/01-modules-intro/scopes-working.view/user.js
  1-js/13-modules/01-modules-intro/scopes.view/hello.js
  1-js/13-modules/01-modules-intro/scopes.view/index.html
  1-js/13-modules/01-modules-intro/scopes.view/user.js
  1-js/13-modules/03-modules-dynamic-imports/say.view/index.html
  1-js/13-modules/03-modules-dynamic-imports/say.view/say.js
Labels: review needed

#648 Update translation of 1-js/11-async/01-callbacks
  1-js/11-async/01-callbacks/01-animate-circle-callback/task.md
  1-js/11-async/01-callbacks/article.md
Labels: review needed

#649 Update translation of 1-js/11-async/02-promise-basics
  1-js/11-async/02-promise-basics/01-re-resolve/solution.md
  1-js/11-async/02-promise-basics/01-re-resolve/task.md
  1-js/11-async/02-promise-basics/02-delay-promise/solution.md
  1-js/11-async/02-promise-basics/02-delay-promise/task.md
  1-js/11-async/02-promise-basics/03-animate-circle-promise/task.md
  1-js/11-async/02-promise-basics/article.md
Labels: review needed

#650 Update translation of 1-js/11-async/03-promise-chaining
  1-js/11-async/03-promise-chaining/01-then-vs-catch/solution.md
  1-js/11-async/03-promise-chaining/01-then-vs-catch/task.md
  1-js/11-async/03-promise-chaining/article.md
Labels: review needed

#653 Update solution.md and solution.js files for many tasks
  1-js/02-first-steps/01-hello-world/1-hello-alert/index.html
  1-js/02-first-steps/01-hello-world/1-hello-alert/solution.md
  1-js/04-object-basics/01-object/3-is-empty/solution.md
Labels: review needed

#651 Update translation of 1-js/11-async/04-promise-error-handling
  1-js/11-async/04-promise-error-handling/01-error-async/solution.md
  1-js/11-async/04-promise-error-handling/01-error-async/task.md
  1-js/11-async/04-promise-error-handling/article.md
Labels: review needed

#654 Update translation of 1-js/11-async/05-promise-api
  1-js/11-async/05-promise-api/article.md
Labels: review needed

#655 Update translation of 1-js/11-async/06-promisify and 07-microtask-queue
  1-js/11-async/06-promisify/article.md
  1-js/11-async/07-microtask-queue/article.md
Labels: review needed

#658 修改错字
  1-js/05-data-types/02-number/2-why-rounded-down/solution.md
Labels: DONE

#657 修改错字
  1-js/05-data-types/02-number/article.md
Labels: DONE

#656 Update translation of 1-js/11-async/08-async-await
  1-js/11-async/08-async-await/01-rewrite-async/solution.md
  1-js/11-async/08-async-await/01-rewrite-async/task.md
  1-js/11-async/08-async-await/02-rewrite-async-2/solution.md
  1-js/11-async/08-async-await/02-rewrite-async-2/task.md
  1-js/11-async/08-async-await/03-async-from-regular/solution.md
  1-js/11-async/08-async-await/03-async-from-regular/task.md
  1-js/11-async/08-async-await/article.md
Labels: review needed

#659 Update translation of 1-js/12-generators-iterators/1-generators
  1-js/12-generators-iterators/1-generators/01-pseudo-random-generator/solution.md
  1-js/12-generators-iterators/1-generators/01-pseudo-random-generator/task.md
  1-js/12-generators-iterators/1-generators/article.md
Labels: review needed

#660 Update translation of 1-js/12-generators-iterators/2-async-iterators-generators
  1-js/12-generators-iterators/2-async-iterators-generators/article.md
Labels: review needed

#661 Update translation of 1-js/13-modules/01-modules-intro
  1-js/13-modules/01-modules-intro/article.md
Labels: review needed

#662 Update translation of 1-js/13-modules/02-import-export
  1-js/13-modules/02-import-export/article.md
Labels: review needed

#664 Update translation of 1-js/99-js-misc/03-currying-partials
  1-js/99-js-misc/03-currying-partials/article.md
Labels: review needed

#663 Update translation of 1-js/99-js-misc/01-proxy
  1-js/99-js-misc/01-proxy/01-error-nonexisting/solution.md
  1-js/99-js-misc/01-proxy/01-error-nonexisting/task.md
  1-js/99-js-misc/01-proxy/02-array-negative/solution.md
  1-js/99-js-misc/01-proxy/02-array-negative/task.md
  1-js/99-js-misc/01-proxy/03-observable/solution.md
  1-js/99-js-misc/01-proxy/03-observable/task.md
  1-js/99-js-misc/01-proxy/article.md
Labels: review needed

#666 Update translation of 2-ui/1-document/02-dom-nodes
  2-ui/1-document/02-dom-nodes/article.md
Labels: review needed

#667 Update translation of 2-ui/1-document/03-dom-navigation
  2-ui/1-document/03-dom-navigation/1-dom-children/solution.md
  2-ui/1-document/03-dom-navigation/1-dom-children/task.md
  2-ui/1-document/03-dom-navigation/3-navigation-links-which-null/solution.md
  2-ui/1-document/03-dom-navigation/3-navigation-links-which-null/task.md
  2-ui/1-document/03-dom-navigation/4-select-diagonal-cells/task.md
  2-ui/1-document/03-dom-navigation/article.md
Labels: review needed

#668 Update translation of 2-ui/1-document/04-searching-elements-dom
  2-ui/1-document/04-searching-elements-dom/1-find-elements/solution.md
  2-ui/1-document/04-searching-elements-dom/1-find-elements/task.md
  2-ui/1-document/04-searching-elements-dom/article.md
Labels: review needed

#669 Update translation of 2-ui/1-document/05-basic-dom-node-properties
  2-ui/1-document/05-basic-dom-node-properties/2-lastchild-nodetype-inline/solution.md
  2-ui/1-document/05-basic-dom-node-properties/2-lastchild-nodetype-inline/task.md
  2-ui/1-document/05-basic-dom-node-properties/2-tree-info/solution.md
  2-ui/1-document/05-basic-dom-node-properties/2-tree-info/task.md
  2-ui/1-document/05-basic-dom-node-properties/3-tag-in-comment/solution.md
  2-ui/1-document/05-basic-dom-node-properties/3-tag-in-comment/task.md
  2-ui/1-document/05-basic-dom-node-properties/4-where-document-in-hierarchy/solution.md
  2-ui/1-document/05-basic-dom-node-properties/4-where-document-in-hierarchy/task.md
  2-ui/1-document/05-basic-dom-node-properties/article.md
Labels: review needed

#670 Update translation of 2-ui/1-document/06-dom-attributes-and-properties
  2-ui/1-document/06-dom-attributes-and-properties/1-get-user-attribute/solution.md
  2-ui/1-document/06-dom-attributes-and-properties/2-yellow-links/solution.md
  2-ui/1-document/06-dom-attributes-and-properties/2-yellow-links/task.md
  2-ui/1-document/06-dom-attributes-and-properties/article.md
Labels: review needed

#671 Update translation of 2-ui/1-document/07-modifying-document
  2-ui/1-document/07-modifying-document/article.md
Labels: review needed

#672 Update translation of 2-ui/1-document/07-modifying-document (task and solution)
  2-ui/1-document/07-modifying-document/1-createtextnode-vs-innerhtml/solution.md
  2-ui/1-document/07-modifying-document/1-createtextnode-vs-innerhtml/task.md
  2-ui/1-document/07-modifying-document/10-clock-setinterval/solution.md
  2-ui/1-document/07-modifying-document/10-clock-setinterval/task.md
  2-ui/1-document/07-modifying-document/11-append-to-list/solution.md
  2-ui/1-document/07-modifying-document/11-append-to-list/task.md
  2-ui/1-document/07-modifying-document/12-sort-table/solution.md
  2-ui/1-document/07-modifying-document/12-sort-table/task.md
  2-ui/1-document/07-modifying-document/4-clear-elem/solution.md
  2-ui/1-document/07-modifying-document/5-why-aaa/solution.md
  2-ui/1-document/07-modifying-document/5-why-aaa/task.md
  2-ui/1-document/07-modifying-document/6-create-list/solution.md
  2-ui/1-document/07-modifying-document/6-create-list/task.md
  2-ui/1-document/07-modifying-document/7-create-object-tree/solution.md
  2-ui/1-document/07-modifying-document/7-create-object-tree/task.md
  2-ui/1-document/07-modifying-document/8-tree-count/solution.md
  2-ui/1-document/07-modifying-document/8-tree-count/task.md
  2-ui/1-document/07-modifying-document/9-calendar-table/solution.md
  2-ui/1-document/07-modifying-document/9-calendar-table/task.md
Labels: WIP, review needed

#673 Update translation of 2-ui/1-document/08-styles-and-classes
  2-ui/1-document/08-styles-and-classes/2-create-notification/task.md
  2-ui/1-document/08-styles-and-classes/article.md
Labels: review needed

#674 Update translation of 2-ui/1-document/09-size-and-scroll
  2-ui/1-document/09-size-and-scroll/1-get-scroll-height-bottom/solution.md
  2-ui/1-document/09-size-and-scroll/1-get-scroll-height-bottom/task.md
  2-ui/1-document/09-size-and-scroll/2-scrollbar-width/solution.md
  2-ui/1-document/09-size-and-scroll/2-scrollbar-width/task.md
  2-ui/1-document/09-size-and-scroll/4-put-ball-in-center/solution.md
  2-ui/1-document/09-size-and-scroll/4-put-ball-in-center/task.md
  2-ui/1-document/09-size-and-scroll/6-width-vs-clientwidth/solution.md
  2-ui/1-document/09-size-and-scroll/6-width-vs-clientwidth/task.md
  2-ui/1-document/09-size-and-scroll/article.md
Labels: review needed

#676 Update translation of 2-ui/1-document/11-coordinates
  2-ui/1-document/11-coordinates/1-find-point-coordinates/solution.md
  2-ui/1-document/11-coordinates/1-find-point-coordinates/solution.view/index.html
  2-ui/1-document/11-coordinates/1-find-point-coordinates/task.md
  2-ui/1-document/11-coordinates/2-position-at/solution.md
  2-ui/1-document/11-coordinates/2-position-at/task.md
  2-ui/1-document/11-coordinates/3-position-at-absolute/solution.md
  2-ui/1-document/11-coordinates/3-position-at-absolute/task.md
  2-ui/1-document/11-coordinates/4-position-inside-absolute/task.md
  2-ui/1-document/11-coordinates/article.md
Labels: review needed

#678 Update from upstream 2020-03-24
  1-js/06-advanced-functions/03-closure/7-let-scope/solution.md
  1-js/06-advanced-functions/04-var/article.md
  1-js/09-classes/01-class/1-rewrite-to-class/_js.view/solution.js
  1-js/09-classes/01-class/1-rewrite-to-class/_js.view/source.js
  1-js/09-classes/01-class/1-rewrite-to-class/solution.md
  1-js/09-classes/01-class/1-rewrite-to-class/task.md
  1-js/09-classes/01-class/article.md
  1-js/09-classes/01-class/class-user.svg
  1-js/09-classes/02-class-inheritance/1-class-constructor-error/solution.md
  1-js/09-classes/02-class-inheritance/1-class-constructor-error/task.md
  1-js/09-classes/02-class-inheritance/2-clock-class-extended/solution.md
  1-js/09-classes/02-class-inheritance/2-clock-class-extended/solution.view/clock.js
  1-js/09-classes/02-class-inheritance/2-clock-class-extended/solution.view/extended-clock.js
  1-js/09-classes/02-class-inheritance/2-clock-class-extended/solution.view/index.html
  1-js/09-classes/02-class-inheritance/2-clock-class-extended/source.view/clock.js
  1-js/09-classes/02-class-inheritance/2-clock-class-extended/source.view/index.html
  1-js/09-classes/02-class-inheritance/2-clock-class-extended/task.md
  1-js/09-classes/02-class-inheritance/3-class-extend-object/rabbit-extends-object.svg
  1-js/09-classes/02-class-inheritance/3-class-extend-object/solution.md
  1-js/09-classes/02-class-inheritance/3-class-extend-object/task.md
  1-js/09-classes/02-class-inheritance/animal-rabbit-extends.svg
  1-js/09-classes/02-class-inheritance/article.md
  1-js/09-classes/02-class-inheritance/class-inheritance-array-object.svg
  1-js/09-classes/02-class-inheritance/class-inheritance-rabbit-animal-2.svg
  1-js/09-classes/02-class-inheritance/class-inheritance-rabbit-animal.svg
  1-js/09-classes/02-class-inheritance/rabbit-animal-independent-animal.svg
  1-js/09-classes/02-class-inheritance/rabbit-animal-independent-rabbit.svg
  1-js/09-classes/02-class-inheritance/super-homeobject-wrong.svg
  1-js/09-classes/02-class-inheritance/this-super-loop.svg
  1-js/09-classes/03-static-properties-methods/animal-rabbit-static.svg
  1-js/09-classes/03-static-properties-methods/article.md
  1-js/09-classes/04-private-protected-properties-methods/article.md
  1-js/09-classes/04-private-protected-properties-methods/coffee-inside.jpg
  1-js/09-classes/04-private-protected-properties-methods/coffee.jpg
  1-js/09-classes/05-extend-natives/article.md
  1-js/09-classes/05-extend-natives/object-date-inheritance.svg
  1-js/09-classes/06-instanceof/1-strange-instanceof/solution.md
  1-js/09-classes/06-instanceof/1-strange-instanceof/task.md
  1-js/09-classes/06-instanceof/article.md
  1-js/09-classes/06-instanceof/instanceof.svg
  1-js/09-classes/07-mixins/article.md
  1-js/09-classes/07-mixins/head.html
  1-js/09-classes/07-mixins/mixin-inheritance.svg
  1-js/09-classes/index.md
Labels: review needed

#681 Update en-comparison from upstream 2020-0324
  1-js/02-first-steps/01-hello-world/1-hello-alert/index.html
  1-js/02-first-steps/01-hello-world/1-hello-alert/solution.md
  1-js/02-first-steps/11-logical-operators/2-alert-or/solution.md
  1-js/02-first-steps/16-arrow-functions-basics/article.md
  1-js/03-code-quality/03-comments/article.md
  1-js/04-object-basics/01-object/article.md
  1-js/05-data-types/04-array/article.md
  1-js/05-data-types/11-date/8-format-date-relative/solution.md
  1-js/05-data-types/11-date/8-format-date-relative/task.md
  1-js/06-advanced-functions/09-call-apply-decorators/article.md
  1-js/08-prototypes/02-function-prototype/article.md
  1-js/09-classes/02-class-inheritance/2-clock-class-extended/solution.view/extended-clock.js
  1-js/09-classes/02-class-inheritance/3-class-extend-object/task.md
  1-js/09-classes/02-class-inheritance/article.md
  1-js/10-error-handling/2-custom-errors/article.md
  1-js/11-async/01-callbacks/article.md
  1-js/11-async/05-promise-api/article.md
  2-ui/1-document/04-searching-elements-dom/article.md
  2-ui/1-document/07-modifying-document/9-calendar-table/solution.md
  2-ui/1-document/09-size-and-scroll/4-put-ball-in-center/ball-half/index.html
  2-ui/1-document/09-size-and-scroll/4-put-ball-in-center/solution.md
  2-ui/1-document/09-size-and-scroll/4-put-ball-in-center/solution.view/index.html
  2-ui/1-document/09-size-and-scroll/4-put-ball-in-center/task.md
Labels: review needed

#682 Update translation to upstream 2020-03-24 commit-162280b
  1-js/02-first-steps/16-arrow-functions-basics/article.md
  1-js/03-code-quality/03-comments/article.md
  1-js/04-object-basics/01-object/article.md
  1-js/05-data-types/11-date/8-format-date-relative/solution.md
  1-js/05-data-types/11-date/8-format-date-relative/task.md
  1-js/08-prototypes/02-function-prototype/article.md
  1-js/10-error-handling/2-custom-errors/article.md
  1-js/11-async/01-callbacks/article.md
  2-ui/1-document/09-size-and-scroll/4-put-ball-in-center/ball-half/index.html
  2-ui/1-document/09-size-and-scroll/4-put-ball-in-center/solution.md
  2-ui/1-document/09-size-and-scroll/4-put-ball-in-center/solution.view/index.html
  2-ui/1-document/09-size-and-scroll/4-put-ball-in-center/task.md
Labels: review needed

#683 Update translation of 2-ui/2-events/01-introduction-browser-events
  2-ui/2-events/01-introduction-browser-events/01-hide-other/task.md
  2-ui/2-events/01-introduction-browser-events/02-hide-self-onclick/solution.md
  2-ui/2-events/01-introduction-browser-events/02-hide-self-onclick/task.md
  2-ui/2-events/01-introduction-browser-events/03-which-handlers-run/solution.md
  2-ui/2-events/01-introduction-browser-events/03-which-handlers-run/task.md
  2-ui/2-events/01-introduction-browser-events/04-move-ball-field/solution.md
  2-ui/2-events/01-introduction-browser-events/04-move-ball-field/task.md
  2-ui/2-events/01-introduction-browser-events/05-sliding-menu/solution.md
  2-ui/2-events/01-introduction-browser-events/06-hide-message/solution.md
  2-ui/2-events/01-introduction-browser-events/06-hide-message/task.md
  2-ui/2-events/01-introduction-browser-events/07-carousel/solution.md
  2-ui/2-events/01-introduction-browser-events/07-carousel/task.md
  2-ui/2-events/01-introduction-browser-events/article.md
Labels: review needed

#684 Update some files 单击 => 点击
  2-ui/1-document/02-dom-nodes/article.md
  2-ui/1-document/09-size-and-scroll/article.md
  2-ui/1-document/11-coordinates/1-find-point-coordinates/solution.view/index.html
  2-ui/1-document/11-coordinates/1-find-point-coordinates/source.view/index.html
  2-ui/1-document/11-coordinates/1-find-point-coordinates/task.md
  2-ui/1-document/11-coordinates/article.md
  2-ui/2-events/01-introduction-browser-events/02-hide-self-onclick/task.md
  2-ui/2-events/01-introduction-browser-events/04-move-ball-field/solution.md
  2-ui/2-events/01-introduction-browser-events/04-move-ball-field/task.md
  2-ui/2-events/01-introduction-browser-events/05-sliding-menu/task.md
  2-ui/2-events/01-introduction-browser-events/article.md
Labels: review needed

#685 Update translation of 2-ui/2-events/02-bubbling-and-capturing
  2-ui/2-events/02-bubbling-and-capturing/article.md
  images.yml
Labels: review needed

#686 Update translation of 2-ui/2-events/03-event-delegation
  2-ui/2-events/03-event-delegation/1-hide-message-delegate/task.md
  2-ui/2-events/03-event-delegation/2-sliding-tree/solution.md
  2-ui/2-events/03-event-delegation/2-sliding-tree/task.md
  2-ui/2-events/03-event-delegation/3-sortable-table/task.md
  2-ui/2-events/03-event-delegation/4-behavior-tooltip/task.md
  2-ui/2-events/03-event-delegation/article.md
  images.yml
Labels: review needed

#687 Update translation of action from 操作/动作 to 行为
  1-js/01-getting-started/1-intro/article.md
  1-js/02-first-steps/02-structure/article.md
  1-js/02-first-steps/07-operators/article.md
  1-js/02-first-steps/14-function-basics/article.md
  1-js/02-first-steps/15-function-expressions/article.md
  1-js/02-first-steps/16-arrow-functions-basics/article.md
  1-js/03-code-quality/01-debugging-chrome/article.md
  1-js/03-code-quality/04-ninja-code/article.md
  1-js/04-object-basics/04-object-methods/article.md
  1-js/05-data-types/04-array/article.md
  1-js/06-advanced-functions/03-closure/1-closure-latest-changes/task.md
  1-js/06-advanced-functions/06-function-object/article.md
  1-js/07-object-properties/01-property-descriptors/article.md
  1-js/11-async/01-callbacks/article.md
  1-js/11-async/03-promise-chaining/article.md
  1-js/11-async/07-microtask-queue/article.md
  1-js/12-generators-iterators/2-async-iterators-generators/article.md
  2-ui/1-document/02-dom-nodes/article.md
  2-ui/1-document/06-dom-attributes-and-properties/article.md
  2-ui/2-events/01-introduction-browser-events/article.md
  2-ui/2-events/03-event-delegation/article.md
Labels: review needed

#688 Update translation of schedule to 计划/调度
  1-js/06-advanced-functions/03-closure/1-closure-latest-changes/task.md
  1-js/06-advanced-functions/08-settimeout-setinterval/4-settimeout-result/task.md
  1-js/06-advanced-functions/08-settimeout-setinterval/article.md
  1-js/06-advanced-functions/10-bind/article.md
  1-js/10-error-handling/1-try-catch/article.md
  1-js/11-async/01-callbacks/article.md
Labels: review needed

#689 Update translation of 2-ui/2-events/04-default-browser-action
  2-ui/2-events/04-default-browser-action/1-why-return-false-fails/solution.md
  2-ui/2-events/04-default-browser-action/1-why-return-false-fails/task.md
  2-ui/2-events/04-default-browser-action/2-catch-link-navigation/solution.md
  2-ui/2-events/04-default-browser-action/2-catch-link-navigation/task.md
  2-ui/2-events/04-default-browser-action/3-image-gallery/solution.md
  2-ui/2-events/04-default-browser-action/3-image-gallery/task.md
  2-ui/2-events/04-default-browser-action/article.md
Labels: review needed

#691 Update translation of wrapper, constructor and constructor function
  1-js/03-code-quality/06-polyfills/article.md
  1-js/04-object-basics/06-constructor-new/3-accumulator/task.md
  1-js/04-object-basics/06-constructor-new/article.md
  1-js/05-data-types/01-primitives-methods/article.md
  1-js/06-advanced-functions/03-closure/4-counter-object-independent/task.md
  1-js/06-advanced-functions/10-bind/article.md
  1-js/06-advanced-functions/12-arrow-functions/article.md
  1-js/08-prototypes/02-function-prototype/article.md
  1-js/08-prototypes/03-native-prototypes/article.md
  1-js/09-classes/01-class/article.md
  1-js/09-classes/02-class-inheritance/article.md
  1-js/09-classes/03-static-properties-methods/article.md
  1-js/10-error-handling/1-try-catch/article.md
  1-js/11-async/02-promise-basics/article.md
  1-js/99-js-misc/01-proxy/article.md
  1-js/99-js-misc/02-eval/article.md
Labels: review needed

#690 Update translation of 2-ui/2-events/05-dispatch-events
  2-ui/2-events/04-default-browser-action/article.md
  2-ui/2-events/05-dispatch-events/article.md
Labels: review needed

#692 Update translation of 2-ui/3-event-details/1-mouse-events-basics
  2-ui/2-events/01-introduction-browser-events/article.md
  2-ui/3-event-details/1-mouse-events-basics/01-selectable-list/task.md
  2-ui/3-event-details/1-mouse-events-basics/article.md
  2-ui/3-event-details/index.md
Labels: needs +1, 正在校对

#693 Update translation of 2-ui/3-event-details/3-mousemove-mouseover-mouseout-mouseenter-mouseleave
  2-ui/2-events/01-introduction-browser-events/article.md
  2-ui/3-event-details/3-mousemove-mouseover-mouseout-mouseenter-mouseleave/1-behavior-nested-tooltip/task.md
  2-ui/3-event-details/3-mousemove-mouseover-mouseout-mouseenter-mouseleave/2-hoverintent/solution.md
  2-ui/3-event-details/3-mousemove-mouseover-mouseout-mouseenter-mouseleave/2-hoverintent/task.md
  2-ui/3-event-details/3-mousemove-mouseover-mouseout-mouseenter-mouseleave/article.md
  2-ui/3-event-details/3-mousemove-mouseover-mouseout-mouseenter-mouseleave/mouseenter-mouseleave-delegation-2.view/script.js
Labels: review needed

#697 Update translation of 操作符 and 运算符
  1-js/02-first-steps/07-operators/1-increment-order/solution.md
  1-js/02-first-steps/07-operators/1-increment-order/task.md
  1-js/02-first-steps/08-comparison/article.md
  1-js/02-first-steps/10-ifelse/article.md
  1-js/02-first-steps/11-logical-operators/article.md
  1-js/02-first-steps/12-while-for/article.md
  1-js/02-first-steps/17-javascript-specials/article.md
  1-js/04-object-basics/05-object-toprimitive/article.md
  1-js/99-js-misc/01-proxy/article.md
Labels: review needed

#698 Update translation of 操作符 and 运算符
  1-js/02-first-steps/04-variables/article.md
  1-js/03-code-quality/05-testing-mocha/article.md
  1-js/04-object-basics/01-object/article.md
  1-js/05-data-types/04-array/article.md
Labels: review needed

#694 Update translation of 2-ui/3-event-details/4-mouse-drag-and-drop and other parts content
  1-js/09-classes/06-instanceof/article.md
  1-js/10-error-handling/2-custom-errors/article.md
  2-ui/1-document/04-searching-elements-dom/article.md
  2-ui/1-document/09-size-and-scroll/article.md
  2-ui/1-document/10-size-and-scroll-window/article.md
  2-ui/2-events/01-introduction-browser-events/04-move-ball-field/task.md
  2-ui/2-events/02-bubbling-and-capturing/article.md
  2-ui/2-events/03-event-delegation/4-behavior-tooltip/task.md
  2-ui/2-events/05-dispatch-events/article.md
  2-ui/3-event-details/1-mouse-events-basics/article.md
  2-ui/3-event-details/3-mousemove-mouseover-mouseout-mouseenter-mouseleave/article.md
  2-ui/3-event-details/4-mouse-drag-and-drop/1-slider/solution.md
  2-ui/3-event-details/4-mouse-drag-and-drop/1-slider/task.md
  2-ui/3-event-details/4-mouse-drag-and-drop/2-drag-heroes/solution.md
  2-ui/3-event-details/4-mouse-drag-and-drop/2-drag-heroes/solution.view/index.html
  2-ui/3-event-details/4-mouse-drag-and-drop/2-drag-heroes/solution.view/soccer.js
  2-ui/3-event-details/4-mouse-drag-and-drop/2-drag-heroes/source.view/index.html
  2-ui/3-event-details/4-mouse-drag-and-drop/2-drag-heroes/task.md
  2-ui/3-event-details/4-mouse-drag-and-drop/article.md
  3-frames-and-windows/03-cross-window-communication/article.md
Labels: review needed

#699 Update translation of 2-ui/3-event-details/5-keyboard-events
  2-ui/3-event-details/5-keyboard-events/2-check-sync-keydown/solution.md
  2-ui/3-event-details/5-keyboard-events/2-check-sync-keydown/solution.view/index.html
  2-ui/3-event-details/5-keyboard-events/2-check-sync-keydown/task.md
  2-ui/3-event-details/5-keyboard-events/article.md
Labels: review needed

#700 Update translation of 2-ui/3-event-details/8-onscroll and README of this repo.
  2-ui/3-event-details/8-onscroll/1-endless-page/solution.md
  2-ui/3-event-details/8-onscroll/1-endless-page/task.md
  2-ui/3-event-details/8-onscroll/2-updown-button/task.md
  2-ui/3-event-details/8-onscroll/3-load-visible-img/solution.md
  2-ui/3-event-details/8-onscroll/3-load-visible-img/task.md
  2-ui/3-event-details/8-onscroll/article.md
  README.md
Labels: review needed
