Repository javascript-tutorial/zh.javascript.info, pull requests merged in 2020-07, with the labels that each got.

#763 modify: change '很' to '能'
  1-js/02-first-steps/04-variables/article.md
Labels: needs +1

#762 修改错误字词
  3-frames-and-windows/03-cross-window-communication/article.md
Labels: needs +1

#765 Update some charactors to [Jun 28, 2020] Part-2
  1-js/02-first-steps/12-nullish-coalescing-operator/article.md
  1-js/02-first-steps/13-while-for/1-loop-last-value/solution.md
  1-js/02-first-steps/13-while-for/1-loop-last-value/task.md
  1-js/02-first-steps/13-while-for/2-which-value-while/solution.md
  1-js/02-first-steps/13-while-for/2-which-value-while/task.md
  1-js/02-first-steps/13-while-for/3-which-value-for/solution.md
  1-js/02-first-steps/13-while-for/3-which-value-for/task.md
  1-js/02-first-steps/13-while-for/4-for-even/solution.md
  1-js/02-first-steps/13-while-for/4-for-even/task.md
  1-js/02-first-steps/13-while-for/5-replace-for-while/solution.md
  1-js/02-first-steps/13-while-for/5-replace-for-while/task.md
  1-js/02-first-steps/13-while-for/6-repeat-until-correct/solution.md
  1-js/02-first-steps/13-while-for/6-repeat-until-correct/task.md
  1-js/02-first-steps/13-while-for/7-list-primes/solution.md
  1-js/02-first-steps/13-while-for/7-list-primes/task.md
  1-js/02-first-steps/13-while-for/article.md
  1-js/02-first-steps/14-switch/1-rewrite-switch-if-else/solution.md
  1-js/02-first-steps/14-switch/1-rewrite-switch-if-else/task.md
  1-js/02-first-steps/14-switch/2-rewrite-if-switch/solution.md
  1-js/02-first-steps/14-switch/2-rewrite-if-switch/task.md
  1-js/02-first-steps/14-switch/article.md
  1-js/02-first-steps/15-function-basics/1-if-else-required/solution.md
  1-js/02-first-steps/15-function-basics/1-if-else-required/task.md
  1-js/02-first-steps/15-function-basics/2-rewrite-function-question-or/solution.md
  1-js/02-first-steps/15-function-basics/2-rewrite-function-question-or/task.md
  1-js/02-first-steps/15-function-basics/3-min/solution.md
  1-js/02-first-steps/15-function-basics/3-min/task.md
  1-js/02-first-steps/15-function-basics/4-pow/solution.md
  1-js/02-first-steps/15-function-basics/4-pow/task.md
  1-js/02-first-steps/15-function-basics/article.md
  1-js/02-first-steps/16-function-expressions/article.md
  1-js/02-first-steps/17-arrow-functions-basics/1-rewrite-arrow/solution.md
  1-js/02-first-steps/17-arrow-functions-basics/1-rewrite-arrow/task.md
  1-js/02-first-steps/17-arrow-functions-basics/article.md
  1-js/02-first-steps/18-javascript-specials/article.md
Labels: review needed

#764 Update some charactors from upstream to [Jun 28, 2020] Part-1
  1-js/02-first-steps/06-alert-prompt-confirm/article.md
  1-js/02-first-steps/07-type-conversions/article.md
  1-js/02-first-steps/08-operators/3-primitive-conversions-questions/solution.md
  1-js/02-first-steps/08-operators/4-fix-prompt/solution.md
  1-js/02-first-steps/08-operators/4-fix-prompt/task.md
  1-js/02-first-steps/08-operators/article.md
  1-js/02-first-steps/09-comparison/article.md
  1-js/02-first-steps/11-logical-operators/article.md
Labels: needs +1

#770 删除多余注释
  1-js/05-data-types/11-date/article.md
Labels: needs +1

#766 Update some chapters to [Jun 28, 2020] Part-3
  1-js/02-first-steps/15-function-basics/article.md
  1-js/02-first-steps/18-javascript-specials/article.md
  1-js/03-code-quality/02-coding-style/article.md
  1-js/03-code-quality/04-ninja-code/article.md
  1-js/03-code-quality/05-testing-mocha/beforeafter.view/test.js
  1-js/04-object-basics/01-object/4-const-object/solution.md
  1-js/04-object-basics/01-object/4-const-object/task.md
  1-js/04-object-basics/01-object/article.md
  1-js/04-object-basics/02-object-copy/article.md
  1-js/04-object-basics/02-object-copy/variable-contains-reference.svg
  1-js/04-object-basics/02-object-copy/variable-copy-reference.svg
  1-js/04-object-basics/02-object-copy/variable-copy-value.svg
  1-js/04-object-basics/03-garbage-collection/article.md
  1-js/04-object-basics/03-garbage-collection/family-delete-refs.svg
  1-js/04-object-basics/03-garbage-collection/family-no-family.svg
  1-js/04-object-basics/03-garbage-collection/family-no-father-2.svg
  1-js/04-object-basics/03-garbage-collection/family-no-father.svg
  1-js/04-object-basics/03-garbage-collection/family.svg
  1-js/04-object-basics/03-garbage-collection/garbage-collection-1.svg
  1-js/04-object-basics/03-garbage-collection/garbage-collection-2.svg
  1-js/04-object-basics/03-garbage-collection/garbage-collection-3.svg
  1-js/04-object-basics/03-garbage-collection/garbage-collection-4.svg
  1-js/04-object-basics/03-garbage-collection/garbage-collection-5.svg
  1-js/04-object-basics/03-garbage-collection/memory-user-john-admin.svg
  1-js/04-object-basics/03-garbage-collection/memory-user-john-lost.svg
  1-js/04-object-basics/03-garbage-collection/memory-user-john.svg
  1-js/04-object-basics/04-object-methods/article.md
  1-js/04-object-basics/07-optional-chaining/article.md
  1-js/04-object-basics/08-symbol/article.md
  1-js/04-object-basics/09-object-toprimitive/article.md
  1-js/05-data-types/04-array/3-call-array-this/solution.md
  1-js/05-data-types/04-array/article.md
  1-js/05-data-types/05-array-methods/12-reduce-object/_js.view/test.js
  1-js/05-data-types/05-array-methods/12-reduce-object/task.md
  1-js/05-data-types/07-map-set/article.md
  1-js/05-data-types/09-keys-values-entries/article.md
Labels: needs +1

#781 修改错误格式和翻译
  8-web-components/7-shadow-dom-events/article.md
Labels: needs +1

#780 Fix some link and typo error
  2-ui/3-event-details/4-mouse-drag-and-drop/1-slider/solution.md
  2-ui/4-forms-controls/2-focus-blur/article.md
  2-ui/4-forms-controls/3-events-change-input/article.md
  2-ui/5-loading/01-onload-ondomcontentloaded/article.md
  2-ui/5-loading/03-onload-onerror/article.md
Labels: needs +1

#782 Fix minor typo error of 1-js/10-error-handling/1-try-catch/article.md
  1-js/10-error-handling/1-try-catch/article.md
Labels: needs +1

#785 Fix minor typo error of 1-js/05-data-types/10-destructuring-assignment/article.md
  1-js/05-data-types/10-destructuring-assignment/article.md
Labels: needs +1

#787 Fix some typo error
  5-network/05-fetch-crossorigin/article.md
  5-network/11-websocket/article.md
Labels: needs +1

#778 Update translation related to PR-766, Part-1
  1-js/02-first-steps/15-function-basics/article.md
  1-js/02-first-steps/18-javascript-specials/article.md
  1-js/03-code-quality/05-testing-mocha/beforeafter.view/test.js
Labels: needs +1

#774 Update translation related to PR-764, Part-1
  1-js/02-first-steps/06-alert-prompt-confirm/article.md
Labels: needs +1

#786 Update translation related to PR-766, Part-3
  1-js/04-object-basics/07-optional-chaining/article.md
Labels: ready to merge

#793 Improve translation of some parts
  1-js/02-first-steps/06-alert-prompt-confirm/article.md
  1-js/02-first-steps/15-function-basics/article.md
  1-js/02-first-steps/18-javascript-specials/article.md
  1-js/03-code-quality/05-testing-mocha/beforeafter.view/test.js
Labels: review needed

#779 Update translation related to PR-766, Part-2
  1-js/04-object-basics/01-object/article.md
  1-js/04-object-basics/02-object-copy/article.md
Labels: needs +1

#777 pr764-4: 1-js/02-first-steps/09-comparison
  1-js/02-first-steps/09-comparison/article.md
Labels: needs +1

#776 pr764-3: 1-js/02-first-steps/11-logical-operators/
  1-js/02-first-steps/11-logical-operators/article.md
Labels: WIP

#775 pr764-2 1-js/02-first-steps/08-operators/4-fix-prompt/
  1-js/02-first-steps/08-operators/4-fix-prompt/solution.md
  1-js/02-first-steps/08-operators/4-fix-prompt/task.md
  1-js/02-first-steps/08-operators/article.md
Labels: WIP

#768 Update some chapters to [Jul 17, 2020] Part-4
  1-js/05-data-types/02-number/article.md
  1-js/05-data-types/10-destructuring-assignment/article.md
  1-js/05-data-types/11-date/6-get-seconds-today/solution.md
  1-js/06-advanced-functions/02-rest-parameters-spread/article.md
  1-js/06-advanced-functions/03-closure/9-sort-by-field/_js.view/solution.js
  1-js/06-advanced-functions/03-closure/9-sort-by-field/_js.view/source.js
  1-js/06-advanced-functions/03-closure/9-sort-by-field/_js.view/test.js
  1-js/06-advanced-functions/03-closure/9-sort-by-field/solution.md
  1-js/06-advanced-functions/04-var/article.md
  1-js/06-advanced-functions/06-function-object/5-sum-many-brackets/_js.view/solution.js
  1-js/06-advanced-functions/06-function-object/5-sum-many-brackets/_js.view/source.js
  1-js/06-advanced-functions/06-function-object/5-sum-many-brackets/_js.view/test.js
  1-js/06-advanced-functions/09-call-apply-decorators/04-throttle/_js.view/test.js
  1-js/06-advanced-functions/09-call-apply-decorators/04-throttle/task.md
  1-js/06-advanced-functions/09-call-apply-decorators/article.md
  1-js/07-object-properties/02-property-accessors/article.md
  1-js/08-prototypes/04-prototype-methods/article.md
Labels: review needed

#794 Update some chapters to [Jul 17, 2020] Part-5
  1-js/08-prototypes/04-prototype-methods/article.md
  1-js/09-classes/01-class/article.md
  1-js/09-classes/02-class-inheritance/article.md
  1-js/09-classes/03-static-properties-methods/3-class-extend-object/rabbit-extends-object.svg
  1-js/09-classes/03-static-properties-methods/3-class-extend-object/solution.md
  1-js/09-classes/03-static-properties-methods/3-class-extend-object/task.md
  1-js/09-classes/07-mixins/article.md
  1-js/09-classes/07-mixins/head.html
  1-js/10-error-handling/1-try-catch/article.md
  1-js/11-async/05-promise-api/article.md
  1-js/12-generators-iterators/2-async-iterators-generators/article.md
  1-js/12-generators-iterators/2-async-iterators-generators/head.html
  1-js/13-modules/01-modules-intro/article.md
  1-js/13-modules/02-import-export/article.md
  1-js/99-js-misc/01-proxy/article.md
  1-js/99-js-misc/04-reference-type/2-check-syntax/solution.md
  1-js/99-js-misc/04-reference-type/2-check-syntax/task.md
  1-js/99-js-misc/04-reference-type/3-why-this/solution.md
  1-js/99-js-misc/04-reference-type/3-why-this/task.md
  1-js/99-js-misc/04-reference-type/article.md
Labels: review needed

#795 Update some chapters to [Jul 17, 2020] Part-6
  2-ui/1-document/01-browser-environment/article.md
  2-ui/1-document/07-modifying-document/article.md
  2-ui/1-document/09-size-and-scroll/article.md
  2-ui/1-document/11-coordinates/article.md
  2-ui/2-events/01-introduction-browser-events/article.md
  2-ui/2-events/03-event-delegation/article.md
  2-ui/2-events/05-dispatch-events/article.md
  2-ui/3-event-details/1-mouse-events-basics/article.md
  2-ui/3-event-details/1-mouse-events-basics/head.html
  2-ui/3-event-details/4-mouse-drag-and-drop/article.md
  2-ui/3-event-details/4-mouse-drag-and-drop/ball.view/index.html
  2-ui/3-event-details/4-mouse-drag-and-drop/ball2.view/index.html
  2-ui/3-event-details/6-pointer-events/article.md
  2-ui/3-event-details/6-pointer-events/ball-2.view/index.html
  2-ui/3-event-details/6-pointer-events/ball.view/index.html
  2-ui/3-event-details/6-pointer-events/multitouch.view/index.html
  2-ui/3-event-details/6-pointer-events/slider.view/index.html
  2-ui/3-event-details/6-pointer-events/slider.view/style.css
  2-ui/3-event-details/7-keyboard-events/2-check-sync-keydown/solution.md
  2-ui/3-event-details/7-keyboard-events/2-check-sync-keydown/solution.view/index.html
  2-ui/3-event-details/7-keyboard-events/2-check-sync-keydown/task.md
  2-ui/3-event-details/7-keyboard-events/article.md
  2-ui/3-event-details/7-keyboard-events/german-layout.svg
  2-ui/3-event-details/7-keyboard-events/keyboard-dump.view/index.html
  2-ui/3-event-details/7-keyboard-events/keyboard-dump.view/script.js
  2-ui/3-event-details/7-keyboard-events/keyboard-dump.view/style.css
  2-ui/3-event-details/7-keyboard-events/us-layout.svg
Labels: review needed

#789 1-js/02-first-steps/12-nullish-coalescing-operator
  1-js/02-first-steps/12-nullish-coalescing-operator/article.md
Labels: WIP

#796 Update some chapters to [Jul 17, 2020] Part-7
  5-network/05-fetch-crossorigin/article.md
  5-network/11-websocket/article.md
  6-data-storage/01-cookie/article.md
  6-data-storage/03-indexeddb/article.md
Labels: Updating

#799 Update from upstream to 2020-07-18
  1-js/02-first-steps/10-ifelse/article.md
  1-js/02-first-steps/12-nullish-coalescing-operator/article.md
  1-js/03-code-quality/02-coding-style/1-style-errors/solution.md
  1-js/04-object-basics/03-garbage-collection/article.md
  1-js/04-object-basics/08-symbol/article.md
  1-js/08-prototypes/04-prototype-methods/article.md
  1-js/09-classes/06-instanceof/article.md
  1-js/11-async/04-promise-error-handling/article.md
  2-ui/3-event-details/4-mouse-drag-and-drop/ball.view/index.html
  3-frames-and-windows/03-cross-window-communication/sandbox.view/index.html
  6-data-storage/02-localstorage/article.md
Labels: review needed

#797 Update from upstream july commit 4583
  1-js/02-first-steps/05-types/article.md
  1-js/02-first-steps/06-alert-prompt-confirm/article.md
  1-js/02-first-steps/10-ifelse/article.md
  1-js/02-first-steps/12-nullish-coalescing-operator/article.md
  1-js/03-code-quality/02-coding-style/1-style-errors/solution.md
  1-js/04-object-basics/03-garbage-collection/article.md
  1-js/04-object-basics/07-optional-chaining/article.md
  1-js/04-object-basics/08-symbol/article.md
  1-js/04-object-basics/09-object-toprimitive/article.md
  1-js/06-advanced-functions/03-closure/7-let-scope/solution.md
  1-js/06-advanced-functions/09-call-apply-decorators/04-throttle/task.md
  1-js/06-advanced-functions/10-bind/article.md
  1-js/08-prototypes/04-prototype-methods/article.md
  1-js/09-classes/06-instanceof/article.md
  1-js/10-error-handling/1-try-catch/article.md
  1-js/11-async/04-promise-error-handling/article.md
  1-js/99-js-misc/01-proxy/01-error-nonexisting/task.md
  1-js/99-js-misc/01-proxy/article.md
  2-ui/1-document/07-modifying-document/article.md
  2-ui/2-events/05-dispatch-events/article.md
  2-ui/3-event-details/1-mouse-events-basics/article.md
  2-ui/3-event-details/4-mouse-drag-and-drop/ball.view/index.html
  3-frames-and-windows/03-cross-window-communication/sandbox.view/index.html
  5-network/05-fetch-crossorigin/article.md
  5-network/07-url/article.md
  6-data-storage/02-localstorage/article.md
Labels: Updating

#803 Update article.md
  2-ui/99-ui-misc/02-selection-range/article.md
Labels: needs +1

#805 Fix minor typo error in 1-js/05-data-types/02-number/article.md
  1-js/05-data-types/02-number/article.md
Labels: needs +1

#801 Translate some chapters to [Jul 17, 2020] part4
  1-js/05-data-types/10-destructuring-assignment/article.md
  1-js/06-advanced-functions/04-var/article.md
  1-js/06-advanced-functions/09-call-apply-decorators/04-throttle/task.md
  1-js/06-advanced-functions/09-call-apply-decorators/article.md
Labels: needs +1, review needed
