Repository javascript-tutorial/zh.javascript.info, pull requests merged in 2020-09, with the labels that each got.

#821 Update article.md
  1-js/08-prototypes/02-function-prototype/article.md
Labels: needs +1

#822 修复一处笔误
  1-js/06-advanced-functions/10-bind/article.md
Labels: needs +1

#809 Update article.md
  1-js/05-data-types/05-array-methods/article.md
Labels: needs +1

#807 Translate some chapters to [Jul 17, 2020] Part-7 #796
  6-data-storage/03-indexeddb/article.md
Labels: needs +1, review needed

#810 add translation of 1-js/99-js-misc/04-reference-type
  1-js/99-js-misc/04-reference-type/article.md
Labels: needs +1

#811 translate some missing contents
  1-js/09-classes/01-class/article.md
  1-js/09-classes/02-class-inheritance/article.md
Labels: needs +1

#831 fix: extend-natives
  1-js/09-classes/05-extend-natives/article.md
Labels: needs +1

#832 ADD: translation of some sentences
  1-js/10-error-handling/1-try-catch/article.md
Labels: review needed

#828 Fix minor typo error
  1-js/02-first-steps/15-function-basics/article.md
Labels: review needed
