Repository javascript-tutorial/zh.javascript.info, pull requests merged in 2020-11, with the labels that each got.

#842 UPD: update to 2020-10-15
  1-js/02-first-steps/02-structure/article.md
  1-js/02-first-steps/08-operators/article.md
  1-js/02-first-steps/09-comparison/article.md
  1-js/02-first-steps/10-ifelse/article.md
  1-js/02-first-steps/11-logical-operators/6-check-if-in-range/task.md
  1-js/02-first-steps/11-logical-operators/7-check-if-out-range/task.md
  1-js/02-first-steps/11-logical-operators/9-check-login/solution.md
  1-js/02-first-steps/11-logical-operators/article.md
  1-js/02-first-steps/12-nullish-coalescing-operator/article.md
  1-js/02-first-steps/13-while-for/article.md
  1-js/02-first-steps/18-javascript-specials/article.md
  1-js/03-code-quality/04-ninja-code/article.md
  1-js/04-object-basics/01-object/8-multiply-numeric/task.md
  1-js/04-object-basics/02-object-copy/article.md
  1-js/04-object-basics/04-object-methods/4-object-property-this/solution.md
  1-js/04-object-basics/04-object-methods/4-object-property-this/task.md
  1-js/04-object-basics/04-object-methods/article.md
  1-js/04-object-basics/07-optional-chaining/article.md
  1-js/04-object-basics/08-symbol/article.md
  1-js/05-data-types/01-primitives-methods/article.md
  1-js/05-data-types/03-string/article.md
  1-js/05-data-types/04-array/article.md
  1-js/05-data-types/05-array-methods/2-filter-range/task.md
  1-js/05-data-types/05-array-methods/6-calculator-extendable/_js.view/solution.js
  1-js/05-data-types/05-array-methods/8-sort-objects/solution.md
  1-js/05-data-types/05-array-methods/article.md
  1-js/05-data-types/06-iterable/article.md
  1-js/05-data-types/11-date/1-new-date/solution.md
  1-js/05-data-types/11-date/article.md
  1-js/06-advanced-functions/01-recursion/article.md
  1-js/06-advanced-functions/03-closure/10-make-army/lexenv-makearmy-empty.svg
  1-js/06-advanced-functions/03-closure/10-make-army/lexenv-makearmy-for-fixed.svg
  1-js/06-advanced-functions/03-closure/10-make-army/lexenv-makearmy-while-fixed.svg
  1-js/06-advanced-functions/03-closure/10-make-army/lexenv-makearmy.svg
  1-js/06-advanced-functions/03-closure/10-make-army/solution.md
  1-js/06-advanced-functions/03-closure/10-make-army/task.md
  1-js/06-advanced-functions/03-closure/article.md
  1-js/06-advanced-functions/04-var/article.md
  1-js/06-advanced-functions/05-global-object/article.md
  1-js/06-advanced-functions/09-call-apply-decorators/03-debounce/solution.md
  1-js/06-advanced-functions/09-call-apply-decorators/03-debounce/task.md
  1-js/06-advanced-functions/09-call-apply-decorators/04-throttle/task.md
  1-js/06-advanced-functions/10-bind/article.md
  1-js/07-object-properties/01-property-descriptors/article.md
  1-js/08-prototypes/01-prototype-inheritance/article.md
  1-js/08-prototypes/03-native-prototypes/article.md
  1-js/09-classes/02-class-inheritance/article.md
  1-js/09-classes/07-mixins/article.md
  1-js/11-async/02-promise-basics/article.md
  1-js/11-async/08-async-await/article.md
  1-js/99-js-misc/05-bigint/article.md
Labels: DONE

#848 UPD: update to 2020-10-15
  1-js/12-generators-iterators/2-async-iterators-generators/article.md
  1-js/99-js-misc/01-proxy/article.md
  1-js/99-js-misc/04-reference-type/article.md
  1-js/99-js-misc/05-bigint/article.md
  2-ui/1-document/05-basic-dom-node-properties/article.md
  2-ui/1-document/10-size-and-scroll-window/article.md
  2-ui/1-document/11-coordinates/article.md
  2-ui/2-events/02-bubbling-and-capturing/article.md
  2-ui/2-events/05-dispatch-events/article.md
  2-ui/3-event-details/1-mouse-events-basics/article.md
  2-ui/3-event-details/6-pointer-events/article.md
  2-ui/3-event-details/8-onscroll/1-endless-page/solution.md
  2-ui/4-forms-controls/1-form-elements/article.md
  2-ui/4-forms-controls/2-focus-blur/article.md
  2-ui/5-loading/02-script-async-defer/article.md
  2-ui/5-loading/03-onload-onerror/article.md
  2-ui/99-ui-misc/01-mutation-observer/article.md
  2-ui/99-ui-misc/02-selection-range/article.md
  2-ui/99-ui-misc/03-event-loop/article.md
  3-frames-and-windows/01-popup-windows/article.md
  3-frames-and-windows/03-cross-window-communication/article.md
  4-binary/01-arraybuffer-binary-arrays/article.md
  4-binary/03-blob/article.md
  5-network/04-fetch-abort/article.md
  5-network/05-fetch-crossorigin/article.md
  5-network/05-fetch-crossorigin/xhr-another-domain.svg
  5-network/05-fetch-crossorigin/xhr-preflight.svg
  5-network/06-fetch-api/article.md
  5-network/07-url/article.md
  5-network/08-xmlhttprequest/article.md
  5-network/10-long-polling/article.md
  5-network/11-websocket/article.md
  6-data-storage/01-cookie/article.md
  6-data-storage/02-localstorage/article.md
  6-data-storage/03-indexeddb/article.md
Labels: DONE

#845 8-web-components/2-custom-elements
  8-web-components/2-custom-elements/article.md
Labels: DONE

#820 Catastrophic backtracking
  9-regular-expressions/15-regexp-catastrophic-backtracking/article.md
Labels: review needed

#843 Translate: 1-js/06-advanced-functions/09-call-apply-decorators/03-debounce
  1-js/06-advanced-functions/09-call-apply-decorators/03-debounce/solution.md
  1-js/06-advanced-functions/09-call-apply-decorators/03-debounce/task.md
Labels: needs +1
