Repository javascript-tutorial/zh.javascript.info, pull requests merged in 2020-02, with the labels that each got.

#590 9-regular-expressions tiny update
  1-js/05-data-types/09-keys-values-entries/article.md
  1-js/05-data-types/11-date/6-get-seconds-today/task.md
  9-regular-expressions/05-regexp-multiline-mode/article.md
  9-regular-expressions/07-regexp-escaping/article.md
  9-regular-expressions/08-regexp-character-sets-and-ranges/article.md
  9-regular-expressions/09-regexp-quantifiers/2-find-html-colors-6hex/solution.md
  9-regular-expressions/10-regexp-greedy-and-lazy/article.md
  9-regular-expressions/11-regexp-groups/02-find-webcolor-3-or-6/solution.md
Labels: needs +1

#592 Backreferences in pattern: \N and \k<name>
  1-js/06-advanced-functions/01-recursion/article.md
  1-js/10-error-handling/1-try-catch/article.md
  9-regular-expressions/12-regexp-backreferences/article.md
Labels: needs +1

#595 Fix typo
  1-js/99-js-misc/03-currying-partials/article.md
Labels: needs +1

#575 Update translation of 1-js/04-object-basics/05-object-toprimitive
  1-js/04-object-basics/05-object-toprimitive/article.md
Labels: changes requested

#578 Update translation of 1-js/04-object-basics/06-constructor-new
  1-js/04-object-basics/06-constructor-new/1-two-functions-one-object/solution.md
  1-js/04-object-basics/06-constructor-new/1-two-functions-one-object/task.md
  1-js/04-object-basics/06-constructor-new/2-calculator-constructor/solution.md
  1-js/04-object-basics/06-constructor-new/2-calculator-constructor/task.md
  1-js/04-object-basics/06-constructor-new/3-accumulator/task.md
  1-js/04-object-basics/06-constructor-new/article.md
Labels: changes requested

#581 Update translation of 01-primitives-methods
  1-js/05-data-types/01-primitives-methods/1-string-new-property/solution.md
  1-js/05-data-types/01-primitives-methods/1-string-new-property/task.md
  1-js/05-data-types/01-primitives-methods/article.md
Labels: needs +1

#597 Update translation of 1-js/05-data-types/02-number
  1-js/05-data-types/02-number/1-sum-interface/solution.md
  1-js/05-data-types/02-number/1-sum-interface/task.md
  1-js/05-data-types/02-number/2-why-rounded-down/solution.md
  1-js/05-data-types/02-number/2-why-rounded-down/task.md
  1-js/05-data-types/02-number/3-repeat-until-number/_js.view/test.js
  1-js/05-data-types/02-number/3-repeat-until-number/solution.md
  1-js/05-data-types/02-number/3-repeat-until-number/task.md
  1-js/05-data-types/02-number/4-endless-loop-error/solution.md
  1-js/05-data-types/02-number/8-random-min-max/solution.md
  1-js/05-data-types/02-number/8-random-min-max/task.md
  1-js/05-data-types/02-number/9-random-int-min-max/solution.md
  1-js/05-data-types/02-number/9-random-int-min-max/task.md
  1-js/05-data-types/02-number/article.md
Labels: review needed

#598 Update translation of 1-js/05-data-types/03-string
  1-js/05-data-types/03-string/1-ucfirst/solution.md
  1-js/05-data-types/03-string/1-ucfirst/task.md
  1-js/05-data-types/03-string/2-check-spam/solution.md
  1-js/05-data-types/03-string/3-truncate/_js.view/test.js
  1-js/05-data-types/03-string/3-truncate/solution.md
  1-js/05-data-types/03-string/3-truncate/task.md
  1-js/05-data-types/03-string/4-extract-currency/task.md
  1-js/05-data-types/03-string/article.md
Labels: review needed

#599 Update translation of 1-js/05-data-types/04-array
  1-js/05-data-types/04-array/10-maximal-subarray/_js.view/test.js
  1-js/05-data-types/04-array/10-maximal-subarray/solution.md
  1-js/05-data-types/04-array/10-maximal-subarray/task.md
  1-js/05-data-types/04-array/2-create-array/solution.md
  1-js/05-data-types/04-array/2-create-array/task.md
  1-js/05-data-types/04-array/3-call-array-this/solution.md
  1-js/05-data-types/04-array/5-array-input-sum/solution.md
  1-js/05-data-types/04-array/article.md
Labels: review needed

#604 Update article.md
  2-ui/4-forms-controls/1-form-elements/article.md
Labels: needs +1

#601 typo: seeters -> setters
  1-js/08-prototypes/04-prototype-methods/article.md
Labels: needs +1

#602 Update translation of 1-js/05-data-types/05-array-methods
  1-js/05-data-types/05-array-methods/1-camelcase/_js.view/solution.js
  1-js/05-data-types/05-array-methods/1-camelcase/task.md
  1-js/05-data-types/05-array-methods/10-average-age/task.md
  1-js/05-data-types/05-array-methods/11-array-unique/solution.md
  1-js/05-data-types/05-array-methods/11-array-unique/task.md
  1-js/05-data-types/05-array-methods/12-reduce-object/task.md
  1-js/05-data-types/05-array-methods/2-filter-range/solution.md
  1-js/05-data-types/05-array-methods/2-filter-range/task.md
  1-js/05-data-types/05-array-methods/3-filter-range-in-place/_js.view/solution.js
  1-js/05-data-types/05-array-methods/3-filter-range-in-place/solution.md
  1-js/05-data-types/05-array-methods/3-filter-range-in-place/task.md
  1-js/05-data-types/05-array-methods/4-sort-back/task.md
  1-js/05-data-types/05-array-methods/5-copy-sort-array/task.md
  1-js/05-data-types/05-array-methods/6-array-get-names/task.md
  1-js/05-data-types/05-array-methods/6-calculator-extendable/solution.md
  1-js/05-data-types/05-array-methods/6-calculator-extendable/task.md
  1-js/05-data-types/05-array-methods/7-map-objects/solution.md
  1-js/05-data-types/05-array-methods/7-map-objects/task.md
  1-js/05-data-types/05-array-methods/8-sort-objects/solution.md
  1-js/05-data-types/05-array-methods/8-sort-objects/task.md
  1-js/05-data-types/05-array-methods/9-shuffle/solution.md
  1-js/05-data-types/05-array-methods/9-shuffle/task.md
  1-js/05-data-types/05-array-methods/article.md
Labels: review needed

#589 1-js/05-data-types/07-map-set/
  1-js/05-data-types/07-map-set/article.md
Labels: needs +1

#606 Update translation of 1-js/05-data-types/06-iterable
  1-js/05-data-types/06-iterable/article.md
Labels: review needed

#607 Update translation of 1-js/05-data-types/07-map-set
  1-js/05-data-types/07-map-set/article.md
Labels: needs +1

#608 Update translation of 1-js/05-data-types/07-map-set
  1-js/05-data-types/07-map-set/01-array-unique-map/task.md
  1-js/05-data-types/07-map-set/02-filter-anagrams/solution.md
  1-js/05-data-types/07-map-set/02-filter-anagrams/task.md
  1-js/05-data-types/07-map-set/03-iterable-keys/solution.md
  1-js/05-data-types/07-map-set/03-iterable-keys/task.md
  1-js/05-data-types/07-map-set/article.md
Labels: WIP, review needed

#610 Fix typo
  1-js/05-data-types/06-iterable/article.md
Labels: needs +1

#611 Update some fix from upstream
  1-js/02-first-steps/02-structure/article.md
  1-js/02-first-steps/03-strict-mode/article.md
  1-js/02-first-steps/05-types/article.md
  1-js/02-first-steps/06-type-conversions/article.md
  1-js/02-first-steps/07-operators/3-primitive-conversions-questions/solution.md
  1-js/02-first-steps/07-operators/3-primitive-conversions-questions/task.md
  1-js/02-first-steps/07-operators/article.md
  1-js/02-first-steps/08-comparison/1-comparison-questions/solution.md
  1-js/04-object-basics/01-object/article.md
  1-js/04-object-basics/03-symbol/article.md
  1-js/05-data-types/03-string/article.md
  1-js/05-data-types/04-array/10-maximal-subarray/task.md
  1-js/05-data-types/04-array/array-pop.svg
  1-js/05-data-types/04-array/array-shift.svg
  1-js/05-data-types/04-array/array-speed.svg
  1-js/05-data-types/04-array/queue.svg
  1-js/05-data-types/04-array/stack.svg
  1-js/05-data-types/05-array-methods/12-reduce-object/task.md
  1-js/05-data-types/05-array-methods/reduce.svg
Labels: WIP, review needed

#612 Update translation of 1-js/05-data-types/09-keys-values-entries
  1-js/05-data-types/09-keys-values-entries/01-sum-salaries/solution.md
  1-js/05-data-types/09-keys-values-entries/01-sum-salaries/task.md
  1-js/05-data-types/09-keys-values-entries/02-count-properties/task.md
  1-js/05-data-types/09-keys-values-entries/article.md
Labels: review needed

#613 Update translation of 1-js/05-data-types/10-destructuring-assignment
  1-js/05-data-types/10-destructuring-assignment/1-destruct-user/solution.md
  1-js/05-data-types/10-destructuring-assignment/1-destruct-user/task.md
  1-js/05-data-types/10-destructuring-assignment/6-max-salary/task.md
  1-js/05-data-types/10-destructuring-assignment/article.md
  1-js/05-data-types/10-destructuring-assignment/destructuring-complex.svg
Labels: WIP, review needed

#614 Update translation of 1-js/05-data-types/11-date
  1-js/05-data-types/11-date/1-new-date/solution.md
  1-js/05-data-types/11-date/2-get-week-day/solution.md
  1-js/05-data-types/11-date/2-get-week-day/task.md
  1-js/05-data-types/11-date/3-weekday/solution.md
  1-js/05-data-types/11-date/3-weekday/task.md
  1-js/05-data-types/11-date/4-get-date-ago/solution.md
  1-js/05-data-types/11-date/4-get-date-ago/task.md
  1-js/05-data-types/11-date/5-last-day-of-month/solution.md
  1-js/05-data-types/11-date/5-last-day-of-month/task.md
  1-js/05-data-types/11-date/6-get-seconds-today/solution.md
  1-js/05-data-types/11-date/6-get-seconds-today/task.md
  1-js/05-data-types/11-date/7-get-seconds-to-tomorrow/solution.md
  1-js/05-data-types/11-date/7-get-seconds-to-tomorrow/task.md
  1-js/05-data-types/11-date/8-format-date-relative/solution.md
  1-js/05-data-types/11-date/8-format-date-relative/task.md
  1-js/05-data-types/11-date/article.md
Labels: review needed

#615 Update translation of 1-js/05-data-types/12-json
  1-js/05-data-types/12-json/1-serialize-object/task.md
  1-js/05-data-types/12-json/2-serialize-event-circular/solution.md
  1-js/05-data-types/12-json/2-serialize-event-circular/task.md
  1-js/05-data-types/12-json/article.md
  1-js/05-data-types/12-json/json-meetup.svg
Labels: review needed

#616 Update translation of 1-js/06-advanced-functions/01-recursion
  1-js/06-advanced-functions/01-recursion/01-sum-to/solution.md
  1-js/06-advanced-functions/01-recursion/01-sum-to/task.md
  1-js/06-advanced-functions/01-recursion/02-factorial/solution.md
  1-js/06-advanced-functions/01-recursion/02-factorial/task.md
  1-js/06-advanced-functions/01-recursion/03-fibonacci-numbers/fibonacci-recursion-tree.svg
  1-js/06-advanced-functions/01-recursion/03-fibonacci-numbers/solution.md
  1-js/06-advanced-functions/01-recursion/03-fibonacci-numbers/task.md
  1-js/06-advanced-functions/01-recursion/04-output-single-linked-list/solution.md
  1-js/06-advanced-functions/01-recursion/05-output-single-linked-list-reverse/solution.md
  1-js/06-advanced-functions/01-recursion/article.md
Labels: review needed

#617 Update translation of 1-js/06-advanced-functions/02-rest-parameters-spread
  1-js/06-advanced-functions/02-rest-parameters-spread/article.md
Labels: review needed

#618 Update translation of 1-js/06-advanced-functions/03-closure
  1-js/06-advanced-functions/03-closure/1-closure-latest-changes/solution.md
  1-js/06-advanced-functions/03-closure/1-closure-latest-changes/task.md
  1-js/06-advanced-functions/03-closure/10-make-army/_js.view/solution.js
  1-js/06-advanced-functions/03-closure/10-make-army/_js.view/source.js
  1-js/06-advanced-functions/03-closure/10-make-army/_js.view/test.js
  1-js/06-advanced-functions/03-closure/10-make-army/lexenv-makearmy.svg
  1-js/06-advanced-functions/03-closure/10-make-army/solution.md
  1-js/06-advanced-functions/03-closure/10-make-army/task.md
  1-js/06-advanced-functions/03-closure/2-closure-variable-access/lexenv-nested-work.svg
  1-js/06-advanced-functions/03-closure/2-closure-variable-access/solution.md
  1-js/06-advanced-functions/03-closure/2-closure-variable-access/task.md
  1-js/06-advanced-functions/03-closure/3-counter-independent/solution.md
  1-js/06-advanced-functions/03-closure/3-counter-independent/task.md
  1-js/06-advanced-functions/03-closure/4-counter-object-independent/solution.md
  1-js/06-advanced-functions/03-closure/4-counter-object-independent/task.md
  1-js/06-advanced-functions/03-closure/5-function-in-if/solution.md
  1-js/06-advanced-functions/03-closure/5-function-in-if/task.md
  1-js/06-advanced-functions/03-closure/6-closure-sum/solution.md
  1-js/06-advanced-functions/03-closure/6-closure-sum/task.md
  1-js/06-advanced-functions/03-closure/7-let-scope/solution.md
  1-js/06-advanced-functions/03-closure/7-let-scope/task.md
  1-js/06-advanced-functions/03-closure/8-filter-through-function/_js.view/solution.js
  1-js/06-advanced-functions/03-closure/8-filter-through-function/_js.view/source.js
  1-js/06-advanced-functions/03-closure/8-filter-through-function/_js.view/test.js
  1-js/06-advanced-functions/03-closure/8-filter-through-function/solution.md
  1-js/06-advanced-functions/03-closure/8-filter-through-function/task.md
  1-js/06-advanced-functions/03-closure/8-make-army/lexenv-makearmy.svg
  1-js/06-advanced-functions/03-closure/9-sort-by-field/solution.md
  1-js/06-advanced-functions/03-closure/9-sort-by-field/task.md
  1-js/06-advanced-functions/03-closure/article.md
  1-js/06-advanced-functions/03-closure/closure-function-declaration.svg
  1-js/06-advanced-functions/03-closure/closure-makecounter-environment.svg
  1-js/06-advanced-functions/03-closure/closure-makecounter-nested-call-2.svg
  1-js/06-advanced-functions/03-closure/closure-makecounter-nested-call.svg
  1-js/06-advanced-functions/03-closure/closure-makecounter.svg
  1-js/06-advanced-functions/03-closure/closure-variable-phrase.svg
  1-js/06-advanced-functions/03-closure/lexenv-if.svg
  1-js/06-advanced-functions/03-closure/lexenv-nested-makecounter-1.svg
  1-js/06-advanced-functions/03-closure/lexenv-nested-makecounter-2.svg
  1-js/06-advanced-functions/03-closure/lexenv-nested-makecounter-3.svg
  1-js/06-advanced-functions/03-closure/lexenv-nested-makecounter-4.svg
  1-js/06-advanced-functions/03-closure/lexenv-nested-makecounter-5.svg
  1-js/06-advanced-functions/03-closure/lexenv-nested-makecounter-6.svg
  1-js/06-advanced-functions/03-closure/lexenv-nested-work.svg
  1-js/06-advanced-functions/03-closure/lexical-environment-global-2.svg
  1-js/06-advanced-functions/03-closure/lexical-environment-global-3.svg
  1-js/06-advanced-functions/03-closure/lexical-environment-global.svg
  1-js/06-advanced-functions/03-closure/lexical-environment-simple-lookup.svg
  1-js/06-advanced-functions/03-closure/lexical-environment-simple.svg
  1-js/06-advanced-functions/03-closure/lexical-search-order.svg
  1-js/06-advanced-functions/03-closure/variable-scope-lookup.svg
Labels: review needed

#619 Update translation of 1-js/06-advanced-functions/03-closure
  1-js/06-advanced-functions/03-closure/1-closure-latest-changes/solution.md
  1-js/06-advanced-functions/03-closure/1-closure-latest-changes/task.md
  1-js/06-advanced-functions/03-closure/10-make-army/solution.md
  1-js/06-advanced-functions/03-closure/10-make-army/task.md
  1-js/06-advanced-functions/03-closure/2-closure-variable-access/solution.md
  1-js/06-advanced-functions/03-closure/2-closure-variable-access/task.md
  1-js/06-advanced-functions/03-closure/3-counter-independent/solution.md
  1-js/06-advanced-functions/03-closure/3-counter-independent/task.md
  1-js/06-advanced-functions/03-closure/4-counter-object-independent/solution.md
  1-js/06-advanced-functions/03-closure/4-counter-object-independent/task.md
  1-js/06-advanced-functions/03-closure/5-function-in-if/solution.md
  1-js/06-advanced-functions/03-closure/5-function-in-if/task.md
  1-js/06-advanced-functions/03-closure/6-closure-sum/task.md
  1-js/06-advanced-functions/03-closure/7-let-scope/solution.md
  1-js/06-advanced-functions/03-closure/7-let-scope/task.md
  1-js/06-advanced-functions/03-closure/8-filter-through-function/solution.md
  1-js/06-advanced-functions/03-closure/8-filter-through-function/task.md
  1-js/06-advanced-functions/03-closure/9-sort-by-field/task.md
  1-js/06-advanced-functions/03-closure/article.md
Labels: review needed

#620 Update translation of 1-js/06-advanced-functions/04-var and minor update of other files
  1-js/02-first-steps/07-operators/article.md
  1-js/04-object-basics/04-object-methods/article.md
  1-js/06-advanced-functions/03-closure/article.md
  1-js/06-advanced-functions/04-var/article.md
Labels: review needed

#622 Update translation of 1-js/06-advanced-functions/05-global-object
  1-js/06-advanced-functions/05-global-object/article.md
Labels: review needed

#623 Update translation of 1-js/06-advanced-functions/06-function-object
  1-js/06-advanced-functions/06-function-object/2-counter-inc-dec/solution.md
  1-js/06-advanced-functions/06-function-object/2-counter-inc-dec/task.md
  1-js/06-advanced-functions/06-function-object/5-sum-many-brackets/solution.md
  1-js/06-advanced-functions/06-function-object/5-sum-many-brackets/task.md
  1-js/06-advanced-functions/06-function-object/article.md
Labels: review needed

#624 Update translation 1-js/06-advanced-functions/08-settimeout-setinterval
  1-js/06-advanced-functions/08-settimeout-setinterval/1-output-numbers-100ms/solution.md
  1-js/06-advanced-functions/08-settimeout-setinterval/1-output-numbers-100ms/task.md
  1-js/06-advanced-functions/08-settimeout-setinterval/3-rewrite-settimeout/solution.md
  1-js/06-advanced-functions/08-settimeout-setinterval/3-rewrite-settimeout/task.md
  1-js/06-advanced-functions/08-settimeout-setinterval/4-settimeout-result/solution.md
  1-js/06-advanced-functions/08-settimeout-setinterval/4-settimeout-result/task.md
  1-js/06-advanced-functions/08-settimeout-setinterval/article.md
  1-js/06-advanced-functions/08-settimeout-setinterval/setinterval-interval.svg
  1-js/06-advanced-functions/08-settimeout-setinterval/settimeout-interval.svg
Labels: review needed
