Repository javascript-tutorial/zh.javascript.info, pull requests merged in 2020-04, with the labels that each got.

#701 Update translation of 2-ui/4-forms-controls/1-form-elements
  2-ui/3-event-details/8-onscroll/2-updown-button/task.md
  2-ui/4-forms-controls/1-form-elements/1-add-select-option/solution.md
  2-ui/4-forms-controls/1-form-elements/1-add-select-option/task.md
  2-ui/4-forms-controls/1-form-elements/article.md
  2-ui/4-forms-controls/index.md
Labels: review needed

#702 Update translation of 2-ui/4-forms-controls/2-focus-blur
  2-ui/1-document/09-size-and-scroll/4-put-ball-in-center/task.md
  2-ui/1-document/11-coordinates/1-find-point-coordinates/task.md
  2-ui/4-forms-controls/2-focus-blur/3-editable-div/solution.view/index.html
  2-ui/4-forms-controls/2-focus-blur/3-editable-div/source.view/index.html
  2-ui/4-forms-controls/2-focus-blur/3-editable-div/task.md
  2-ui/4-forms-controls/2-focus-blur/4-edit-td-click/solution.md
  2-ui/4-forms-controls/2-focus-blur/4-edit-td-click/task.md
  2-ui/4-forms-controls/2-focus-blur/5-keyboard-mouse/solution.md
  2-ui/4-forms-controls/2-focus-blur/5-keyboard-mouse/solution.view/index.html
  2-ui/4-forms-controls/2-focus-blur/5-keyboard-mouse/source.view/index.html
  2-ui/4-forms-controls/2-focus-blur/5-keyboard-mouse/task.md
  2-ui/4-forms-controls/2-focus-blur/article.md
Labels: review needed

#703 Update translation of 2-ui/4-forms-controls/3-events-change-input and 4-forms-submit
  2-ui/4-forms-controls/3-events-change-input/1-deposit-calculator/task.md
  2-ui/4-forms-controls/3-events-change-input/article.md
  2-ui/4-forms-controls/4-forms-submit/1-modal-dialog/solution.md
  2-ui/4-forms-controls/4-forms-submit/1-modal-dialog/task.md
  2-ui/4-forms-controls/4-forms-submit/article.md
Labels: review needed

#679 Add translation of 8-web-components/4-template-element/article.md
  8-web-components/4-template-element/article.md
Labels: needs +1, ready to merge

#704 Update translation of 2-ui/5-loading/01-onload-ondomcontentloaded
  2-ui/5-loading/01-onload-ondomcontentloaded/article.md
Labels: review needed

#705 Update translation of 2-ui/5-loading/02-script-async-defer, 03-onload-onerror and other files
  1-js/01-getting-started/1-intro/article.md
  1-js/03-code-quality/02-coding-style/article.md
  1-js/06-advanced-functions/06-function-object/article.md
  1-js/11-async/03-promise-chaining/article.md
  1-js/13-modules/02-import-export/article.md
  1-js/13-modules/03-modules-dynamic-imports/article.md
  2-ui/1-document/05-basic-dom-node-properties/article.md
  2-ui/2-events/04-default-browser-action/3-image-gallery/task.md
  2-ui/5-loading/02-script-async-defer/article.md
  2-ui/5-loading/03-onload-onerror/1-load-img-callback/solution.md
  2-ui/5-loading/03-onload-onerror/1-load-img-callback/task.md
  2-ui/5-loading/03-onload-onerror/article.md
Labels: review needed

#707 Update translation of 2-ui/99-ui-misc/01-mutation-observer and 1-js/05-data-types/01-primitives-methods/article.md
  1-js/05-data-types/01-primitives-methods/article.md
  2-ui/99-ui-misc/01-mutation-observer/article.md
Labels: review needed

#708 Update translation of 2-ui/99-ui-misc/02-selection-range
  2-ui/99-ui-misc/02-selection-range/article.md
Labels: review needed

#709 Update translation of 2-ui/99-ui-misc/03-event-loop and other files
  1-js/05-data-types/01-primitives-methods/article.md
  1-js/10-error-handling/2-custom-errors/article.md
  2-ui/99-ui-misc/03-event-loop/article.md
  7-animation/1-bezier-curve/article.md
  8-web-components/1-webcomponents-intro/article.md
Labels: review needed

#710 Update 04-05 in en-comparison
  1-js/02-first-steps/01-hello-world/article.md
  1-js/02-first-steps/13-switch/article.md
  1-js/02-first-steps/17-javascript-specials/article.md
  1-js/04-object-basics/01-object/article.md
  1-js/04-object-basics/04-object-methods/2-check-syntax/solution.md
  1-js/04-object-basics/04-object-methods/3-why-this/solution.md
  1-js/05-data-types/02-number/article.md
  1-js/06-advanced-functions/01-recursion/article.md
  1-js/06-advanced-functions/02-rest-parameters-spread/article.md
  1-js/06-advanced-functions/03-closure/article.md
  1-js/08-prototypes/04-prototype-methods/article.md
  1-js/09-classes/01-class/article.md
  1-js/99-js-misc/03-currying-partials/article.md
  2-ui/1-document/11-coordinates/1-find-point-coordinates/solution.md
  2-ui/2-events/02-bubbling-and-capturing/article.md
  2-ui/2-events/04-default-browser-action/article.md
  2-ui/2-events/05-dispatch-events/article.md
  2-ui/4-forms-controls/1-form-elements/article.md
  2-ui/5-loading/03-onload-onerror/article.md
Labels: review needed

#711 Update 04-05 in master
  1-js/02-first-steps/01-hello-world/article.md
  1-js/02-first-steps/13-switch/article.md
  1-js/05-data-types/02-number/article.md
  1-js/06-advanced-functions/02-rest-parameters-spread/article.md
  1-js/06-advanced-functions/03-closure/article.md
  1-js/09-classes/01-class/article.md
  1-js/99-js-misc/03-currying-partials/article.md
Labels: review needed

#712 Update translation of 3-frames-and-windows/01-popup-windows and etc.
  3-frames-and-windows/01-popup-windows/article.md
  3-frames-and-windows/index.md
Labels: needs +1, 正在校对

#713 Update translation of 1-js/05-data-types/02-number, 07-map-set/article.md etc.
  1-js/05-data-types/01-primitives-methods/article.md
  1-js/05-data-types/02-number/1-sum-interface/solution.md
  1-js/05-data-types/02-number/1-sum-interface/task.md
  1-js/05-data-types/02-number/2-why-rounded-down/solution.md
  1-js/05-data-types/02-number/2-why-rounded-down/task.md
  1-js/05-data-types/02-number/3-repeat-until-number/solution.md
  1-js/05-data-types/02-number/3-repeat-until-number/task.md
  1-js/05-data-types/02-number/4-endless-loop-error/solution.md
  1-js/05-data-types/02-number/4-endless-loop-error/task.md
  1-js/05-data-types/02-number/8-random-min-max/solution.md
  1-js/05-data-types/02-number/8-random-min-max/task.md
  1-js/05-data-types/02-number/9-random-int-min-max/solution.md
  1-js/05-data-types/02-number/9-random-int-min-max/task.md
  1-js/05-data-types/02-number/article.md
  1-js/05-data-types/07-map-set/article.md
  2-ui/1-document/11-coordinates/article.md
Labels: review needed

#717 Update translation of 检测 to 检查
  1-js/02-first-steps/08-comparison/article.md
  1-js/02-first-steps/11-logical-operators/7-check-if-out-range/task.md
  1-js/03-code-quality/05-testing-mocha/article.md
  1-js/05-data-types/05-array-methods/3-filter-range-in-place/task.md
  2-ui/1-document/03-dom-navigation/article.md
  2-ui/3-event-details/1-mouse-events-basics/article.md
  2-ui/99-ui-misc/02-selection-range/article.md
  5-network/01-fetch/article.md
Labels: review needed

#716 Update translation of 3-frames-and-windows/03-cross-window-communication and etc. files
  1-js/02-first-steps/01-hello-world/article.md
  1-js/02-first-steps/04-variables/article.md
  1-js/09-classes/07-mixins/article.md
  1-js/11-async/03-promise-chaining/01-then-vs-catch/task.md
  2-ui/2-events/01-introduction-browser-events/article.md
  2-ui/2-events/04-default-browser-action/article.md
  2-ui/5-loading/03-onload-onerror/article.md
  3-frames-and-windows/03-cross-window-communication/article.md
Labels: review needed

#719 Update translation of 3-frames-and-windows/06-clickjacking
  1-js/01-getting-started/3-code-editors/article.md
  1-js/03-code-quality/01-debugging-chrome/article.md
  1-js/05-data-types/06-iterable/article.md
  1-js/13-modules/02-import-export/article.md
  3-frames-and-windows/06-clickjacking/article.md
  3-frames-and-windows/06-clickjacking/clickjacking-visible.view/index.html
  3-frames-and-windows/06-clickjacking/clickjacking.view/index.html
  3-frames-and-windows/06-clickjacking/protector.view/iframe.html
  3-frames-and-windows/06-clickjacking/top-location.view/index.html
Labels: review needed

#718 Fix a minor typo error
  7-animation/1-bezier-curve/article.md
Labels: needs +1

#720 Update translation of 4-binary/01-arraybuffer-binary-arrays
  4-binary/01-arraybuffer-binary-arrays/01-concat/task.md
  4-binary/01-arraybuffer-binary-arrays/article.md
Labels: review needed

#721 Update translation of 4-binary/03-blob
  4-binary/03-blob/article.md
Labels: review needed

#722 Update translation of 5-network/01-fetch
  5-network/01-fetch/article.md
Labels: review needed

#723 Update translation of 5-network/02-formdata and etc.
  5-network/01-fetch/01-fetch-users/solution.md
  5-network/01-fetch/01-fetch-users/task.md
  5-network/02-formdata/article.md
Labels: review needed

#724 Update translation of 5-network/05-fetch-crossorigin
  5-network/05-fetch-crossorigin/1-do-we-need-origin/solution.md
  5-network/05-fetch-crossorigin/1-do-we-need-origin/task.md
  5-network/05-fetch-crossorigin/article.md
Labels: review needed

#725 Update translation of 5-network/06-fetch-api
  5-network/06-fetch-api/article.md
Labels: review needed

#675 Add translation of 9-regular-expressions/02-regexp-character-classes/article.md
  9-regular-expressions/02-regexp-character-classes/article.md
Labels: needs +1

#726 Update translation of 5-network/07-url
  5-network/07-url/article.md
Labels: review needed

#727 Update README and translation of 5-network/08-xmlhttprequest
  5-network/08-xmlhttprequest/article.md
  README.md
Labels: review needed

#728 Update translation of 5-network/09-resume-upload and 10-long-polling
  5-network/09-resume-upload/article.md
  5-network/09-resume-upload/upload-resume.view/server.js
  5-network/09-resume-upload/upload-resume.view/uploader.js
  5-network/10-long-polling/article.md
Labels: review needed

#706 Add translation of 3-additional-articles/9-regular-expressions/11-regexp-groups
  9-regular-expressions/11-regexp-groups/article.md
Labels: needs +1, 正在校对

#729 Update translation of 5-network/11-websocket
  5-network/11-websocket/article.md
Labels: review needed

#730 Update translation of 6-data-storage/01-cookie and etc.
  6-data-storage/01-cookie/article.md
  6-data-storage/02-localstorage/1-form-autosave/task.md
  6-data-storage/index.md
Labels: review needed

#695 indexedDB
  6-data-storage/03-indexeddb/article.md
  6-data-storage/03-indexeddb/indexeddb-structure.svg
Labels: needs +1

#733 fix: fix typo in css-transition
  7-animation/2-css-animations/article.md
Labels: needs +1

#734 Correct translation article.md
  1-js/10-error-handling/1-try-catch/article.md
Labels: needs +1

#731 🚑 补充翻译
  9-regular-expressions/08-regexp-character-sets-and-ranges/article.md
Labels: needs +1, ready to merge

#735 Fix minor typo error
  1-js/05-data-types/12-json/article.md
Labels: DONE
