Repository javascript-tutorial/zh.javascript.info, pull requests merged in 2020-05, with the labels that each got.

#736 示例代码中的 JSON 格式错误
  1-js/11-async/03-promise-chaining/article.md
Labels: DONE

#737 单词拼写错误
  1-js/11-async/02-promise-basics/article.md
Labels: needs +1

#740 9-regular-expressions/16-regexp-sticky/
  9-regular-expressions/16-regexp-sticky/article.md
Labels: needs +1

#739 Shadow DOM styling
  8-web-components/6-shadow-dom-style/article.md
Labels: DONE

#631 Add translation of 8-web-components/5-slots-composition/article.md
  8-web-components/5-slots-composition/article.md
Labels: needs +1, review needed
