Repository javascript-tutorial/zh.javascript.info, pull requests merged in 2020-10, with the labels that each got.

#834 Fix: minor typo error
  1-js/08-prototypes/01-prototype-inheritance/article.md
Labels: needs +1

#835 Fix: 将 trap 的翻译从「陷阱」改为「捕捉器」
  1-js/99-js-misc/01-proxy/article.md
Labels: needs +1

#837 fix: fix translation errors
  1-js/02-first-steps/17-arrow-functions-basics/article.md
Labels: needs +1

#839 Fix: improve translation in 1-js/09-classes/02-class-inheritance/article.md
  1-js/09-classes/02-class-inheritance/article.md
Labels: review needed

#841 UPD: from upstream to 2020-10-15
  1-js/01-getting-started/1-intro/article.md
  1-js/01-getting-started/2-manuals-specifications/article.md
  1-js/01-getting-started/3-code-editors/article.md
  1-js/01-getting-started/4-devtools/article.md
  1-js/01-getting-started/4-devtools/bug.html
  1-js/02-first-steps/05-types/article.md
  1-js/02-first-steps/07-type-conversions/article.md
  1-js/02-first-steps/08-operators/article.md
  1-js/02-first-steps/09-comparison/article.md
  1-js/02-first-steps/10-ifelse/article.md
  1-js/02-first-steps/15-function-basics/article.md
  1-js/03-code-quality/02-coding-style/article.md
  1-js/03-code-quality/03-comments/article.md
  1-js/03-code-quality/04-ninja-code/article.md
  1-js/04-object-basics/03-garbage-collection/article.md
  1-js/04-object-basics/08-symbol/article.md
  1-js/05-data-types/12-json/article.md
  1-js/11-async/03-promise-chaining/article.md
  1-js/13-modules/01-modules-intro/article.md
  2-ui/1-document/01-browser-environment/article.md
  7-animation/1-bezier-curve/article.md
  8-web-components/2-custom-elements/article.md
  9-regular-expressions/08-regexp-character-sets-and-ranges/article.md
  9-regular-expressions/13-regexp-alternation/article.md
Labels: WIP, review needed
