Repository javascript-tutorial/zh.javascript.info, pull requests merged in 2020-01, with the labels that each got.

#577 Update tasks of 1-js/05-data-types/05-array-methods and 1-js/04-objec…
  1-js/05-data-types/05-array-methods/12-reduce-object/_js.view/solution.js
  1-js/05-data-types/05-array-methods/12-reduce-object/_js.view/test.js
  1-js/05-data-types/05-array-methods/12-reduce-object/solution.md
  1-js/05-data-types/05-array-methods/12-reduce-object/task.md
  1-js/05-data-types/05-array-methods/6-calculator-extendable/_js.view/solution.js
  1-js/05-data-types/05-array-methods/6-calculator-extendable/_js.view/test.js
  1-js/05-data-types/05-array-methods/6-calculator-extendable/solution.md
  1-js/05-data-types/05-array-methods/6-calculator-extendable/task.md
Labels: review needed

#576 构造函数和操作符 "new" - 总结：其他章节链接
  1-js/04-object-basics/06-constructor-new/article.md
Labels: needs +1

#572 Update translation of 1-js/04-object-basics/03-symbol
  1-js/04-object-basics/03-symbol/article.md
Labels: needs +1

#582 Finished translation for article regexp-unicode
  9-regular-expressions/03-regexp-unicode/article.md
Labels: needs +1, 正在校对

#584 看教程过程中感觉有些不顺的地方
  1-js/04-object-basics/01-object/article.md
  1-js/04-object-basics/06-constructor-new/2-calculator-constructor/task.md
  1-js/04-object-basics/06-constructor-new/article.md
  1-js/05-data-types/01-primitives-methods/1-string-new-property/solution.md
  1-js/05-data-types/01-primitives-methods/article.md
  1-js/05-data-types/02-number/article.md
  1-js/05-data-types/07-map-set/article.md
  1-js/05-data-types/08-weakmap-weakset/article.md
Labels: needs +1

#574 Update translation of 1-js/04-object-basics/04-object-methods
  1-js/04-object-basics/04-object-methods/2-check-syntax/solution.md
  1-js/04-object-basics/04-object-methods/3-why-this/solution.md
  1-js/04-object-basics/04-object-methods/3-why-this/task.md
  1-js/04-object-basics/04-object-methods/4-object-property-this/solution.md
  1-js/04-object-basics/04-object-methods/4-object-property-this/task.md
  1-js/04-object-basics/04-object-methods/7-calculator/solution.md
  1-js/04-object-basics/04-object-methods/7-calculator/task.md
  1-js/04-object-basics/04-object-methods/8-chain-calls/solution.md
  1-js/04-object-basics/04-object-methods/8-chain-calls/task.md
  1-js/04-object-basics/04-object-methods/article.md
Labels: changes requested

#587 tiny translation update
  1-js/05-data-types/03-string/article.md
  1-js/05-data-types/05-array-methods/1-camelcase/task.md
  1-js/05-data-types/05-array-methods/12-reduce-object/task.md
  1-js/05-data-types/05-array-methods/9-shuffle/solution.md
  1-js/05-data-types/05-array-methods/article.md
Labels: needs +1

#585 9-regular-expressions/17-regexp-methods/
  9-regular-expressions/17-regexp-methods/article.md
Labels: needs +1

#569 加入注意事项（已增添到英文版）
  1-js/11-async/02-promise-basics/article.md
Labels: needs +1
