Repository javascript-tutorial/zh.javascript.info, pull requests merged in 2021-06, with the labels that each got.

#916 FIX: fix a typo error in 1-js/02-first-steps/10-ifelse/article.md
  1-js/02-first-steps/10-ifelse/article.md
Labels: needs +1

#885 IMP: improve translation in 1-js/05-data-types/03-string/article.md
  1-js/05-data-types/03-string/article.md
Labels: WIP, needs +1

#905 FIX: fix translation error in 1-js/04-object-basics/09-object-toprimitive/article.md
  1-js/04-object-basics/09-object-toprimitive/article.md
Labels: needs +1

#906 FIX: fix typo error in 1-js/04-object-basics/07-optional-chaining/article.md
  1-js/04-object-basics/07-optional-chaining/article.md
Labels: needs +1

#911 FIX: replace [[FunctionKind]] with [[IsClassConstructor]] in 1-js/09-classes/01-class/article.md
  1-js/09-classes/01-class/article.md
Labels: needs +1

#914 FIX: fix typo error in 1-js/06-advanced-functions/09-call-apply-decorators/03-debounce/task.md
  1-js/06-advanced-functions/09-call-apply-decorators/03-debounce/task.md
Labels: review needed

#909 IMP: improve translation in 1-js/11-async/05-promise-api/article.md
  1-js/11-async/05-promise-api/article.md
Labels: needs +1

#919 FIX: fix typo error in 3-frames-and-windows/06-clickjacking/article.md
  3-frames-and-windows/06-clickjacking/article.md
Labels: needs +1

#922 FIX: correct the layout problem #920
  1-js/05-data-types/10-destructuring-assignment/article.md
Labels: needs +1

#927 FIX: fix minor typo error in 5-network/11-websocket/article.md
  5-network/11-websocket/article.md
Labels: needs +1

#928 FIX: fix minor typo error in 6-data-storage/03-indexeddb/article.md
  6-data-storage/03-indexeddb/article.md
Labels: needs +1
