Repository javascript-tutorial/zh.javascript.info, pull requests merged in 2022-05, with the labels that each got.

#1039 Update to 2022-04
  1-js/02-first-steps/07-type-conversions/article.md
  1-js/02-first-steps/08-operators/article.md
  1-js/02-first-steps/12-nullish-coalescing-operator/article.md
  1-js/02-first-steps/15-function-basics/1-if-else-required/solution.md
  1-js/02-first-steps/15-function-basics/article.md
  1-js/02-first-steps/16-function-expressions/article.md
  1-js/02-first-steps/17-arrow-functions-basics/article.md
  1-js/02-first-steps/18-javascript-specials/article.md
  1-js/03-code-quality/01-debugging-chrome/article.md
  1-js/03-code-quality/06-polyfills/article.md
  1-js/04-object-basics/01-object/article.md
  1-js/04-object-basics/04-object-methods/7-calculator/task.md
  1-js/04-object-basics/04-object-methods/article.md
  1-js/04-object-basics/07-optional-chaining/article.md
  1-js/04-object-basics/08-symbol/article.md
  1-js/04-object-basics/09-object-toprimitive/article.md
  1-js/05-data-types/01-primitives-methods/article.md
  1-js/05-data-types/02-number/article.md
  1-js/05-data-types/04-array/3-call-array-this/task.md
  1-js/05-data-types/04-array/article.md
  1-js/05-data-types/05-array-methods/3-filter-range-in-place/_js.view/test.js
  1-js/05-data-types/10-destructuring-assignment/article.md
  1-js/06-advanced-functions/01-recursion/article.md
  1-js/07-object-properties/02-property-accessors/article.md
  1-js/09-classes/03-static-properties-methods/article.md
  1-js/11-async/05-promise-api/article.md
  1-js/11-async/08-async-await/01-rewrite-async/solution.md
  1-js/11-async/08-async-await/01-rewrite-async/task.md
  1-js/12-generators-iterators/2-async-iterators-generators/article.md
  1-js/13-modules/01-modules-intro/article.md
  1-js/13-modules/02-import-export/article.md
  1-js/99-js-misc/04-reference-type/article.md
  2-ui/1-document/04-searching-elements-dom/article.md
  2-ui/1-document/09-size-and-scroll/article.md
  2-ui/1-document/09-size-and-scroll/metric-client-left-top-rtl.svg
  2-ui/1-document/09-size-and-scroll/metric-client-left-top.svg
  2-ui/2-events/05-dispatch-events/article.md
  2-ui/3-event-details/4-mouse-drag-and-drop/article.md
  2-ui/4-forms-controls/1-form-elements/article.md
  2-ui/4-forms-controls/3-events-change-input/article.md
  2-ui/99-ui-misc/03-event-loop/2-micro-macro-queue/solution.md
  2-ui/99-ui-misc/03-event-loop/2-micro-macro-queue/task.md
  3-frames-and-windows/01-popup-windows/article.md
  3-frames-and-windows/03-cross-window-communication/article.md
  4-binary/01-arraybuffer-binary-arrays/01-concat/_js.view/solution.js
  4-binary/01-arraybuffer-binary-arrays/article.md
  4-binary/03-blob/article.md
  5-network/01-fetch/article.md
  5-network/04-fetch-abort/article.md
  5-network/06-fetch-api/article.md
  5-network/11-websocket/demo.view/server.js
  7-animation/2-css-animations/4-animate-circle-callback/solution.md
  7-animation/2-css-animations/4-animate-circle-callback/solution.view/index.html
  7-animation/2-css-animations/4-animate-circle-callback/task.md
Labels: Updating

#1040 fix: translation error
  2-ui/1-document/06-dom-attributes-and-properties/article.md
Labels: needs +1

#1042 fix: translation in 2-ui/2-events/04-default-browser-action/article.md
  2-ui/2-events/04-default-browser-action/article.md
Labels: needs +1

#1046 fix(typo): fix type in async & defer
  2-ui/5-loading/02-script-async-defer/article.md
Labels: needs +1

#1047 fix: typo error
  1-js/02-first-steps/17-arrow-functions-basics/article.md
Labels: needs +1

#1052 fix: typo error
  1-js/02-first-steps/10-ifelse/article.md
Labels: needs +1

#1050 improve translation for 1-js/05-data-types/10-destructuring-assignment
  1-js/05-data-types/10-destructuring-assignment/article.md
Labels: question, needs +1

#1051 improve translation for 1-js/05-data-types/11-date
  1-js/05-data-types/11-date/article.md
Labels: needs +1

#1054 fix: 解构->结构
  1-js/05-data-types/12-json/article.md
Labels: needs +1
