Repository javascript-tutorial/zh.javascript.info, pull requests merged in 2022-04, with the labels that each got.

#1028 Fix typo
  2-ui/5-loading/02-script-async-defer/article.md
Labels: needs +1

#1024 补充 ** 完成 Markdown Bold 展示
  9-regular-expressions/16-regexp-sticky/article.md
Labels: needs +1

#1023 Fix typo: 因为否则 -> 因为如果允许的话
  2-ui/1-document/08-styles-and-classes/article.md
Labels: needs +1

#1030 fix: Clerical error
  1-js/05-data-types/03-string/article.md
Labels: needs +1

#1032 fix(network/resume-upload): typo
  5-network/09-resume-upload/article.md
Labels: review needed

#1033 Update article.md
  9-regular-expressions/17-regexp-methods/article.md
Labels: needs +1

#1036 fix: translation in 1-js/06-advanced-functions/05-global-object/article.md
  1-js/06-advanced-functions/05-global-object/article.md
Labels: DONE

#1037 Update 1-js/06-advanced-functions/02-rest-parameters-spread/article.md
  1-js/06-advanced-functions/02-rest-parameters-spread/article.md
Labels: needs +1
