Repository javascript-tutorial/zh.javascript.info, pull requests merged in 2022-02, with the labels that each got.

#1002 fix: translation
  2-ui/1-document/04-searching-elements-dom/article.md
Labels: needs +1

#999 Update article.md
  2-ui/1-document/01-browser-environment/article.md
Labels: needs +1

#995 fix: querySelectorAll in 8-web-components/5-slots-composition/article.md
  8-web-components/5-slots-composition/article.md
Labels: needs +1

#994 fix: translation in 1-js/06-advanced-functions/03-closure/article.md
  1-js/06-advanced-functions/03-closure/article.md
Labels: DONE

#993 imp: 1-js/07-object-properties/02-property-accessors/article.md
  1-js/07-object-properties/02-property-accessors/article.md
Labels: needs +1

#988 FIX: fix bug caused by GitHub data change
  1-js/12-generators-iterators/2-async-iterators-generators/article.md
Labels: needs +1

#1005 fix: bug caused by GitHub data change
  1-js/12-generators-iterators/2-async-iterators-generators/article.md
Labels: review needed

#1001 pr issues/1000 feat: add promise.any
  1-js/11-async/05-promise-api/article.md
Labels: changes requested

#974 feat: add translation of 9-regular-expressions/14-regexp-lookahead-lookbehind task and solution
  9-regular-expressions/14-regexp-lookahead-lookbehind/1-find-non-negative-integers/solution.md
  9-regular-expressions/14-regexp-lookahead-lookbehind/1-find-non-negative-integers/task.md
  9-regular-expressions/14-regexp-lookahead-lookbehind/2-insert-after-head/solution.md
  9-regular-expressions/14-regexp-lookahead-lookbehind/2-insert-after-head/task.md
Labels: changes requested

#991 feat: 更新运算符优先级
  1-js/02-first-steps/08-operators/article.md
Labels: WIP, needs +1

#1009 feat: issues/1008
  9-regular-expressions/01-regexp-introduction/article.md
Labels: needs +1

#1006 Update: 更新blob的最新使用方法
  4-binary/03-blob/article.md
Labels: needs +1

#1010 fix: type error
  1-js/05-data-types/09-keys-values-entries/article.md
Labels: needs +1

#1012 Update article.md
  1-js/13-modules/01-modules-intro/article.md
Labels: needs +1

#1011 fix: 修改 promisify 一章中不通顺的地方
  1-js/11-async/06-promisify/article.md
Labels: needs +1

#1014 fix: typo
  1-js/02-first-steps/13-while-for/article.md
Labels: needs +1
