Repository javascript-tutorial/zh.javascript.info, pull requests merged in 2022-07, with the labels that each got.

#1066 fix: typo in 03-string
  1-js/05-data-types/03-string/article.md
Labels: changes requested

#1069 fix: typo in 1-js/04-object-basics/07-optional-chaining/article.md
  1-js/04-object-basics/07-optional-chaining/article.md
Labels: needs +1

#1074 Fix: 1-js/11-async/02-promise-basics/
  1-js/11-async/02-promise-basics/article.md
Labels: needs +1

#1072 fix: 1-js/06-advanced-functions/05-global-object/
  1-js/06-advanced-functions/05-global-object/article.md
Labels: needs +1

#1070 fix: translation of 1-js/06-advanced-functions/03-closure/
  1-js/06-advanced-functions/03-closure/article.md
Labels: needs +1

#1075 fix: 1-js/13-modules/01-modules-intro/
  1-js/13-modules/01-modules-intro/article.md
Labels: needs +1

#1076 fix: 1-js/13-modules/02-import-export
  1-js/13-modules/02-import-export/article.md
Labels: needs +1

#1073 fix: 1-js/06-advanced-functions/06-function-object
  1-js/06-advanced-functions/06-function-object/article.md
Labels: needs +1

#1077 translate: 2-ui/1-document/07-modifying-document
  2-ui/1-document/07-modifying-document/article.md
Labels: needs +1

#1053 improve translation for 1-js/06-advanced-functions/02-rest-parameters-spread
  1-js/06-advanced-functions/02-rest-parameters-spread/article.md
Labels: changes requested

#1079 feat: improve translation 5-network/04-fetch-abort/article.md
  5-network/04-fetch-abort/article.md
Labels: review needed

#1082 fix: typo
  1-js/02-first-steps/10-ifelse/article.md
Labels: needs +1
