Repository javascript-tutorial/zh.javascript.info, pull requests merged in 2022-12, with the labels that each got.

#1132 fix: typo
  1-js/02-first-steps/18-javascript-specials/article.md
Labels: 校对认领, needs +1

#1134 虽然 改为 但是
  1-js/01-getting-started/2-manuals-specifications/article.md
Labels: needs +1

#1135 fix: translation of 1-js/03-code-quality/01-debugging-chrome/article.md
  1-js/03-code-quality/01-debugging-chrome/article.md
Labels: needs +1

#1125 feat: translation 1-js/99-js-misc/06-unicode/article.md
  1-js/99-js-misc/06-unicode/article.md
Labels: review needed
