Repository javascript-tutorial/zh.javascript.info, pull requests merged in 2024-01, with the labels that each got.

#1180 update article.md
  1-js/03-code-quality/06-polyfills/article.md
Labels: review needed

#1188 fix: typo
  1-js/02-first-steps/12-nullish-coalescing-operator/article.md
  1-js/05-data-types/03-string/article.md
  1-js/05-data-types/12-json/article.md
  1-js/08-prototypes/04-prototype-methods/article.md
  1-js/12-generators-iterators/2-async-iterators-generators/article.md
  1-js/99-js-misc/01-proxy/article.md
  1-js/99-js-misc/04-reference-type/article.md
  README.md
Labels: needs +1

#1182 fix: join方法描述缺失
  1-js/05-data-types/05-array-methods/article.md
Labels: question

#1191 Update article.md
  2-ui/2-events/02-bubbling-and-capturing/article.md
Labels: needs +1
